### PR TITLE
Feature/2631 SCC Report Summary page 

### LINKED ISSUE #2631: SCC Report Summary page
## Background
The SCC report has recently been streamlined and a lengthy intro section has been replaced by a short summary page. This ticket aims to save time for Admins by automating some of the content; the rest will require manual population.

## User Story
As an Admin, I would like the SCC summary page to be auto-populated where possible so that I can save time.

## Feature(s) Description

- [ ] Create a Word download as per the format attached
- [ ] Auto-populate the fields according to [this Miro board](https://miro.com/app/board/uXjVL8_J9Js=/?share_link_id=21951296007)
- [ ] Add a new link to the Reports menu as below

[SCC Summary page.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHIrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6cde520a6d70b0820dde1c4523422fc61e7e125/SCC%20Summary%20page.docx)

## Acceptance Criteria
It's done when Admins can produce an SCC summary page at the click of a button.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Nick

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2631

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link: https://jac-admin-develop--pr2641-feat-2631-scc-report-w5b13tuh.web.app/exercise/0ySRDHmWM8ARVxSCw7zv
- Click `SCC Summary Page` of reports menu.
- The SCC summary should have data.
- Enter customised fields and click Download SCC Summary, the SCC data should be included.
Screenshot 2024-12-18 at 09 56 44

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of worke

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC James, are you able to attend to the following points pls:

- Method of shortlisting should reproduce the shortlisting methods in normal English separated by commas, e.g. Name-blind paper sift (NOT name-blind-paper-sift) - as it appears on screen in shortlisting set-up, other options could be Critical analysis qualifying test (QT), Scenario test qualifying test (QT), Situational judgement qualifying test (QT). At the moment is a dropdown box, which needs to be populated by the user.
- Hide the refresh button as it is redundant on this page.
- Selection day tools should be populated from that section of Selection set-up, but is currently appearing blank
- Statutory consultee(s) field should contain the text Insert name(s) or Consultation waived
- Launch and close dates should be formatted in the download in DD/MM/YYYY format

**Comment by nickaddy** [comment]
@KoWeiJAC Selection tools text is displaying but not as it should:
image

Also, apologies, I forgot to mention it the first time, no data is being displayed for Dates of Selection days (correct dates for this exercise shown below:)
image

**Comment by KoWeiJAC** [comment]
> @KoWeiJAC Selection tools text is displaying but not as it should: image
> 
> Also, apologies, I forgot to mention it the first time, no data is being displayed for Dates of Selection days (correct dates for this exercise shown below:) image

@nickaddy 
The the selection tools text and the dates of selection days has been fixed.
Could you confirm them again ? Thanks!

**Review by nickaddy — APPROVED** [review]
Looks great, Ko Wei! Pls close and merge as it's already been to UT.

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
