### PR TITLE
#1723 Diversity Report - Amendments

### LINKED ISSUE #1723: Diversity Report - Amendments
Hi Andrew and Matt,

I just wanted to reach out about a change to the Platform’s Diversity Report section that we would like to make if possible, which addresses an issue that has come up several times in the last fortnight. Apologies if you prefer Slack for this type of issue Andrew, but I thought with the various attachments an email might be easier.

The issue is that we have noticed that the platform diversity report is not currently consistent with other places w[here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1090127/Judicial_diversity_2022_Tables.ods) we report diversity statistics, most notably the annual Combined Statistics Report. This has t[here](https://admin.judicialappointments.digital/exercise/Yt04PxbBde5nfZxNgFWx/reports/diversity)fore caused some confusion when reading from exercise Diversity Checkpoints (which are produced from the Platform reports page). See the attached emails for a couple of examples.

Most significantly, candidates listing their ethnicity as Other are not being included in the BAME category on the diversity reports. However, our agreed policy with JDF partners is that Other comes under the BAME label, including for EMP consideration. The other main inconsistency is that candidates who choose not to disclose their characteristics (“Prefer not to say”) are being included in percentage calculations, so that, for example, the sum of percentages for disabled and non-disabled candidates is not 100%. A final minor difference is the inclusion of a Gender Neutral category in the Gender section. This has an extremely small number of responses so the Stats report just includes this in the Unknown count, so that the comparison between male and female representation can be easily made. 

See below tables as presented in the statistics report (2022 tables can be found here). Note i) no “Other” category for ethnicity, ii) unknowns not included in percentage calculations and iii) no “Gender Neutral” category in gender. To compare, see the diversity reports here for 066 as an example.

We are keen to make a change to the diversity reports as quickly as possible to prevent further confusion. Would you be able to advise on how best we might be able to do this? Happy to chat through further with Jessica and the developers present to fully illustrate the issue and agree our proposed changes.

-------

Hi Sean,

Thank you for sending over the details. Reading through the detail with develops we think one of the requirements is:

•	In apply when a candidate selects “other”  the diversity section on admin should count this as BAME in the diversity report section.

The others we are not sure what you want and how you want it presented, so think a chat is best? The first link didn’t work but I presume you mean this one - [Diversity of the judiciary: 2022 statistics - GOV.UK (www.gov.uk)](https://www.gov.uk/government/statistics/diversity-of-the-judiciary-2022-statistics) and the attached document from this website?

-----------

Hi Sean, 

We have spoken some more and think point 2 is this:

It looks like the second point is that the actual values (e.g. male, female) should add up to 100% with the Prefer Not To Says being reflected outside of this, probably they’ve used Declaration Rate to indicate this. So, for example, out of 10 cats:

•	6 said they prefer Whiskers
•	2 said they prefer Applause
•	2 preferred not to say

The percent would be:

•	75% said they prefer Whiskers (6 out of 8)
•	25% said they prefer Applause (2 out of 8)
•	Declaration rate was 80% (8 out of 10)

-------------------

Our emails have crossed, but yes, the cat analogy is correct. We’d like to apply this to the whole diversity report section (so Applied, Shortlisted, …, Handover) for each characteristic (Gender, Ethnicity, …, Social Mobility). For Social Mobility, it is not clear if the current numbers for Attending State School and First Gen Uni are including or excluding unknowns from the percentage calculation. It would be good to verify that they are excluding them.

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
For the diversity reports:

- candidates listing their ethnicity as Other should be included in the BAME category
- display a declaration rate (see example below)
- candidates who have Not Answered or have selected Other or Prefer Not To Say should not be included in the percentage calculations, eg out of 10 cats:

• 6 said they prefer Whiskers
• 2 said they prefer Applause
• 2 preferred not to say

The percent would be:

• 75% said they prefer Whiskers (6 out of 8)
• 25% said they prefer Applause (2 out of 8)
• Declaration rate was 80% (8 out of 10)

This is linked to the following PRs in Digital Platform:

https://github.com/jac-uk/digital-platform/pull/904
https://github.com/jac-uk/digital-platform/pull/933

And the following PR in Apply: https://github.com/jac-uk/apply/pull/1049

Closes #1723 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
**Please use this Production url to view the diversity report for live exercises:**
https://jac-apply-admin-production--1723-diversity-y27mp62o.web.app/

Go to the diversity report and ensure that the numbers look right according to the criteria above.

Declaration Total has been removed for the following:
- Social Mobility
- EMP Status

Ensure that the Dashboard page reflects the same figures.

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:PRODUCTION
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by tomlovesgithub — APPROVED** [review]

**Review by HalcyonJAC — APPROVED** [review]

**Comment by drieJAC** [comment]
The following exercise can be used for testing:

https://jac-admin-develop--pr2046-feature-1723-diversi-hp3ropno.web.app/exercise/6fqqfchNpqEEqILBonhL/reports/diversity

**Comment by nickaddy** [comment]
@warrensearle I know we talked about this ticket on Monday, but where are we at with it; have we resolved the issues? Does it need to go through UT again?

**Review by NormaJAC — COMMENTED** [review]
Needs UT

**Review by NormaJAC — APPROVED** [review]
declaration total removed

**Review by warrensearle — COMMENTED** [review]
Don't forget to update the Dashboard reports so they match the diversity report 🤓

**Review by warrensearle — APPROVED** [review]

**Comment by drieJAC** [comment]
@nickaddy to chase Sean for feedback on this today

**Comment by JeremykJAC** [comment]
@nickaddy emailed Sean for response yesterday but not heard back yet

**Comment by drieJAC** [comment]
@nickaddy Sean was testing against the url on develop which didnt have all the latest changes I'm afraid. I have updated the link at the top of this page for him to test against. This is on Prodcution.

**Comment by nickaddy** [comment]
Shared new link with Sean, awaiting feedback.

**Comment by nickaddy** [comment]
@warrensearle @drieJAC Just to confirm then, all the changes have already been merged onto the live platform?

**Comment by nickaddy** [comment]
@drieJAC Can you pls review and implement the feedback from Sean below?

Diversity Reports: 
•	I can confirm that the ethnicity mapping (now including “Other” in ethnic minority) seems to be working, having checked against the raw data.
•	The social mobility bits still aren’t working like the other parts, however. For example, exercise 00129, it says there are 265 applications who attended a UK state school, which it calculates is 73.61% - but that means it is dividing by all 360 applications. It should (if consistent with the other parts) be excluding those who do not answer or “Prefer not to say”. If it was doing this I calculate it should be 77.03% attended UK state school. Same with First Generation University which I calculate should say 63.79% (12 prefer not to says to exclude.
•	As mentioned, with both of these, ideally below Attended UK State School it would give a declaration rate, like the categories above. So you know what % declared, and of those who declared, what % went to a UK state school.

Dashboard:
This seems to be working much better in general now thanks, now in line with the percentages in the Div Reports. Just a couple of things:
•	In the table headings (just under graph) it says (eg) “Gender (Applied 356 candidates)”. The problem is there are actually 360 candidates applied, it is just that only 356 declared their gender (if you switch to the Ethnicity panel, it says 352 applied). I think quoting 356 is bound to cause confusion, so we should change this to the total applied. 
•	Social mobility – Same comment applies as in the diversity report. I don’t know if this category is proving more complicated due to it dealing with 2 questions at the same time, rather than one (so two different declaration rates). It could be separated out if that would help. Currently the declaration rate is blank. It also says “Applied undefined candidates” in brackets next to the heading.

**Comment by warrensearle** [comment]
> @drieJAC Can you pls review and implement the feedback from Sean below?

Awesome, thanks @nickaddy yes we'll get on that right away 👍

**Comment by drieJAC** [comment]
In addition to Sean's comments above we just had a chat and he fed back the following...

For both the Dashboard and the Diversity Report in the social mobility section we want the data to show parents who DID NOT attend university (as this tallies with the pre-0104 question regarding the candidate being First Generation To Attend University).

**Comment by drieJAC** [comment]
I also applied a fix for exercises 123, 130 and 164 which should use legacy questions for social mobility as per Sean's instructions.

**Comment by drieJAC** [comment]
'Stats for 'Other' are now being displayed for Professional Background on the Dashboard and the Report as per Sean's request.

**Comment by seancuddz** [comment]
Hi all, just to summarise the changes made and confirm I am happy with this PR to be completed.
Figures for the Dashboard tables/graphs, and on the Diversity report, now all look correct for the exercises I have sampled. "Other" ethnicities are being included in Ethnic Minority count as intended, Gender reporting has been simplified to just Male & Female, Unknowns/Prefer not to says have been excluded from percentage calculations, and a declaration rate calculated beneath the other categories.
The issues with new social mobility data in the report (including the 3 exercises affected by the late switch) appear to have been resolved. Additionally, Other professional background has been taken out of the Unknown/non-declared count, as this is a valid professional background with non-negligible count, particularly for non-legal exercises.
The one outstanding concern is the need to press the Refresh button before figures are displaying correctly. I do worry users (including myself!) will not remember to do this and we will have cases where we have quoted incorrect figures. Would appreciate any fix that might be able to be applied in this area in the future. It is a separate issue to this PR so can deal with elsewhere.
Thanks to @drieJAC @nickaddy and all for their work on this update.

**Comment by nickaddy** [comment]
> Hi all, just to summarise the changes made and confirm I am happy with this PR to be completed. Figures for the Dashboard tables/graphs, and on the Diversity report, now all look correct for the exercises I have sampled. "Other" ethnicities are being included in Ethnic Minority count as intended, Gender reporting has been simplified to just Male & Female, Unknowns/Prefer not to says have been excluded from percentage calculations, and a declaration rate calculated beneath the other categories. The issues with new social mobility data in the report (including the 3 exercises affected by the late switch) appear to have been resolved. Additionally, Other professional background has been taken out of the Unknown/non-declared count, as this is a valid professional background with non-negligible count, particularly for non-legal exercises. The one outstanding concern is the need to press the Refresh button before figures are displaying correctly. I do worry users (including myself!) will not remember to do this and we will have cases where we have quoted incorrect figures. Would appreciate any fix that might be able to be applied in this area in the future. It is a separate issue to this PR so can deal with elsewhere. Thanks to @drieJAC @nickaddy and all for their work on this update.

@seancuddz Thank you for your patience, essential input and insight on this piece of work - much appreciated. @drieJAC Great work on this ticket, thank you for your persistence, focus and dedication!

**Pull request merged**
