### PR TITLE
Search Improvements - Digital Platform 875 

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?

 Add a new empty state pattern.
 Ensure the search works when the user types 3 or more charaters in the search input.
 When performing a search if a valid search term has been passed in then override pagination to use the 'number' format. If the search term is removed or invalid then revert it back to whatever the initial value was.

This PR is linked to issue: https://github.com/jac-uk/digital-platform/issues/875
And PR: https://github.com/jac-uk/digital-platform/pull/920

Closes https://github.com/jac-uk/digital-platform/issues/875

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

When no search results are available there is a new 'empty search results' screen.
See screenshot:
Screenshot 2023-08-08 at 14 28 33

The new search has been implemented on six different search pages.
Each page will have different criteria that can be searched on.
The search requires three characters or more to be typed, ie if you type 'ja' then the search will not execute but if you type 'jac' then it will.
**Be sure to also test the search using the @ symbol and the dot character (if it appears in the email address).**

The list below gives the url of the search page and the criteria that can be searched on:

- Exercises
   See: https://jac-admin-develop--pr2105-feature-dp-875-searc-sloajkfu.web.app/exercises
   Search Criteria: Exercise Title, Exercise Reference Number
- Candidates
   See: https://jac-admin-develop--pr2105-feature-dp-875-searc-sloajkfu.web.app/candidates/
   Search Criteria: Candidate Name, Candidate Email, Candidate NI Number
- Applications
   See: https://jac-admin-develop--pr2105-feature-dp-875-searc-sloajkfu.web.app/exercise/mgiIdf4ccm3z7Q3jsZKb/applications/applied
   Search Criteria: Application Reference Number,  Candidate Name, Candidate Email, Candidate NI Number
- Character Checks
   See: https://jac-admin-develop--pr2105-feature-dp-875-searc-sloajkfu.web.app/exercise/mgiIdf4ccm3z7Q3jsZKb/tasks/character-checks
   Search Criteria: Application Reference Number,  Candidate Name, Candidate Email, Candidate NI Number
- Assessments
   See: https://jac-admin-develop--pr2105-feature-dp-875-searc-sloajkfu.web.app/exercise/mgiIdf4ccm3z7Q3jsZKb/tasks/independent-assessments
   Search Criteria: Application Reference Number,  Candidate Name, Assessor Email, Assessor Name
- Application Records
   See: https://jac-admin-develop--pr2105-feature-dp-875-searc-sloajkfu.web.app/exercise/mgiIdf4ccm3z7Q3jsZKb/stages/review
   Search Criteria: Application Reference Number,  Candidate Name, Candidate Email, Candidate NI Number

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by drieJAC** [comment]
An error was found when testing. If a search is performed using a dot or @ symbol an error appears in the console. This is because these characters cannot be used to search for firestore keys.
A fix has been implemented in DP and Jac-kit to fix this.

**Comment by drieJAC** [comment]
The node scripts with the fix have been deployed to develop and staging

**Review by HalcyonJAC — APPROVED** [review]
Great work 👍

**Review by warrensearle — APPROVED** [review]
👍

**Comment by nickaddy** [comment]
@drieJAC this was the original list of user requests: can you scan through and confirm all of these have been addressed pls?

Exercise search function (doesn't work). Good to search by title (and part title) and ref. no.
2. IA (in ‘tasks’) search function (doesn't work). Search by candidate name (and partial name) and by IA name (and partial name)
3. Character checks search function (doesn’t work) 
4. Add search function to the 'stages' sub categories
5. Ability to search by email [think this is already possible when searching under ‘candidates’ – does it need to be rolled our wider? What are the benefits? Just in terms searching under ‘candidates’ it is not explicitly clear that the search function is also identifying candidates whose emails match the search criteria e.g. if you were to search for a candidate called Brad Pitt by typing the first 3 letters of their surname, Angelina Jolie would also appear in the shortlist of candidate’s. This, at first, would appear to be a bug, until you click through to her profile and see that her email address is pitythefool@gmail.com]
6. Ability to search without having to type what it is exactly e.g. I should be able to find a candidate by typing their name in lower case even though the candidate's name is in upper case on the platform.

**Comment by warrensearle** [comment]
Hey @nickaddy,

> @drieJAC this was the original list of user requests: can you scan through and confirm all of these have been addressed pls? 
> 1. Exercise search function (doesn't work). Good to search by title (and part title) and ref. no. 

✅ Done

> 2. IA (in ‘tasks’) search function (doesn't work). Search by candidate name (and partial name) and by IA name (and partial name) 

✅ Done

> 3. Character checks search function (doesn’t work) 

✅ Done

> 4. Add search function to the 'stages' sub categories 

✅ The existing search on the first Stage has been fixed. The search doesn't currently feature on the other stages however will be added to the other stages as part of #1666

> 5. Ability to search by email [think this is already possible when searching under ‘candidates’ – does it need to be rolled our wider? What are the benefits? 

✅ Done

> Just in terms searching under ‘candidates’ it is not explicitly clear that the search function is also identifying candidates whose emails match the search criteria e.g. if you were to search for a candidate called Brad Pitt by typing the first 3 letters of their surname, Angelina Jolie would also appear in the shortlist of candidate’s. This, at first, would appear to be a bug, until you click through to her profile and see that her email address is [pitythefool@gmail.com](mailto:pitythefool@gmail.com)] 

❌ It sounds like the suggestion here is to improve the UI/UX so the searches knows which fields are being searched on, which in some cases are fields that aren't on display in the list/results. If we want to address this feedback then we should do so in a separate new ticket. There may be a quick win though equally a lot of time could be spent designing and implementing the perfect solution

> 6. Ability to search without having to type what it is exactly e.g. I should be able to find a candidate by typing their name in lower case even though the candidate's name is in upper case on the platform.

✅ Done

**Pull request merged**
