### PR TITLE
WIP #1345 Configure application form content

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?
First iteration of Staged Applications epic.
Here we are enabling the application form to be configured.
The work has involved re-organising our code with the following changes:
 - New folder structure which groups together related code
 - New routing
 - New sub navigation and side navigation
 - Create an exercise journey should now 'work' better than it did

## Who should test?
✅ Product owner
✅ Developers

## How to test?
As there have been lots of code changes it would be good to test the whole Exercise area of admin including:
 - Create an exercise, with a 'journey'. User should expect to be navigated through the selected forms for configuring the exercise
 - Create an exercise without a 'journey'
 - Navigate around and configure a new exercise
 - Navigate around and use an existing exercise including tasks, stages, reports etc.
 - Use the new 'Application form' area to configure which data is requested from the candidate when they apply for the vacancy

## Risk - how likely is this to impact other areas?
🔴 High risk - this includes a lot of changes to shared code

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by KateMJAC** [comment]
This has been sent to the UTG to test the navigation and select/deselect options in the 'Aplication form section'

**Review by KateMJAC — COMMENTED** [review]
This has been sent to the UTG to test the navigation and select/deselect options in the 'Aplication form section' .

Feedback to follow.

**Comment by KateMJAC** [comment]
@warrensearle initial feedback is good from our first tester is good, but need some more feedback from a few more. Se below: 

'I like this new view, it looks a lot cleaner and less cluttered, with more detailed options along the the horizontal axis.'

On the application form page:

'And it did allow me to save and continue after making the choices below. Everything seems to work as it should'

**Comment by joy-ade** [comment]
@warrensearle positive feedback from UTG  see the below

Could you save and continue with your choices?
-Yes – please see screenshots of two trials below; Please note that the order of the selected elements changed after I clicked ‘Save and continue’- e.g. while Personal details appears at the top on the first screenshot below, it moves down to the bottom of the list after clicking on ‘Save and continue’; I am not sure if this is intentional, but it might be easier if the order of the application form parts stays the same after you click ‘Save and continue’.

**Comment by joy-ade** [comment]
@warrensearle There is a bug on stages, while l was updated candidates statues from review to shortlisted. The counter for review on stages is different to the counter for review on task bar  find see below
Capture PNG52

**Review by joy-ade — APPROVED** [review]
Approved by product team and UTG

**Comment by warrensearle** [comment]
Closing as this PR is superseded by further iterations on the Stage Applications epic #1341

**Pull request closed without merging**
