### PR TITLE
#2009 Added filters for exercises

### LINKED ISSUE #2009: Exercise Approval Filter - UT Feedback
On SLs approving exercises - it would be helpful to have a filter on the page with exercises listed where you can filter out exercises that require clearance or if the exercises requiring clearance are identified on the list differently somehow. At the moment, all the exercises that are listed, approved or not, all look the same.

Explore option of adding a filter onto main page of exercises to filter by approval state

### LINKED ISSUE #2011: Late Applications, Finding one - UT Feedback
Again, with late applications, having to locate the exercise that has the late application could be difficult, if there was something the highlighted which exercise has a late application connected to it could be useful, or if the application sends a notification with a link to the SL would be really helpful.

Explore and option for the platform to highlight an exercise with a late application or a flag to show a candidate has one

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
On the exercises list page i added a radio group to the filters to allow the user to filter exercises by 'approval'.
Also added was a checkbox for 'late application requests'.

closes #2009
closes #2011 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
See the video attached:

https://github.com/jac-uk/admin/assets/115651787/2ad66364-dfe4-42f6-a103-27821751b097

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by andrew-isaac — APPROVED** [review]

**Review by HalcyonJAC — COMMENTED** [review]
It seems that it requires an index when `Approved` and `Show late application requests only` are selected.

https://github.com/jac-uk/admin/assets/79906532/feea4fe0-5e57-48ae-bbd0-e4062ea4ea5f

**Comment by drieJAC** [comment]
Ok @HalcyonJAC I have added extra indexes to Digital Platform to support selecting both filters. We have now run out of indexes though so we can't support selecting all 3 of the current filters.

See: https://github.com/jac-uk/digital-platform/pull/886

**Review by HalcyonJAC — APPROVED** [review]
👍

**Review by warrensearle — APPROVED** [review]
All looks good. @drieJAC I've left a comment about moving code to `tableQuery` in the JAC Kit. This can be implemented under a new ticket / PR if you agree with the change.

**Pull request merged**
