### PR TITLE
Feature/2275 Update reports which include stage status

### LINKED ISSUE #2275: Update reports which include stage & status - e.g. diversity report
**Background**
As part of #1666 we need to ensure reports, for example the diversity report, are updated to use the new stages and statuses. Likewise there may be stage and status selector dropdowns which need updating with the latest stages. Many have been fixed and will update automatically but we should check for any stragglers. 

**Features(s)**

1. Identify all places in our code base that use hard-coded stages and statuses so we have a 'hit list' of places to fix and then test, reports, report tabs, filter dropdowns, etc.
2. Make the necessary updates

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2275 

- Update the diversity report to align with the stage changes (from `Selected` to `Selectable`).
- Update the outreach report to align with the stage changes (from `Selected` to `Selectable`).
- Places that use hard-coded stages:
  - "Candidate Breakdown at Each Stage" on the exercise dashboard.
  - "Diversity" report
  - "Outreach" report
- Places that use hard-coded statuses: **(need to check the final version of statuses)**
  - "Character" Issues report
  - "Statutory" Consultation report
  - "applicationCurrentStep" in `src/helpers/exerciseHelper.js`

Note: This PR needs changes on digital-platform: [Feature/admin#2275 Update reports which include stage & status](https://github.com/jac-uk/digital-platform/pull/1008).

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Example exercise: https://jac-admin-develop--pr2295-feature-2275-update-znmzqtya.web.app/exercise/7LgaEMudSSfBC1fOwnaf/dashboard

**Dashboard**
1. Click "Refresh" to refresh the diversity report.
2. Check if "Selectable" appears under "Candidate Breakdown at Each Stage" section.
3. Click "Export data" and open the report. Check if "selectable" appears in the header.

image

**Diversity Report**
1. Click "Refresh" to refresh the diversity report.
2. Check the tab `Selectable` appearing onscreen.
3. Click "Export all data" and open the report. Check if "selectable" appears in the header.

image

**Outreach Report**
1. Click "Refresh" to refresh the outreach report.
2. Check the tab `Selectable` appearing onscreen.
3. Click "Export all data" and open the report. Check if "selectable" appears in the header.

image

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by nickaddy — CHANGES_REQUESTED** [review]
@HalcyonJAC I can see the changes to Diversity and Outreach displays and reports and they look fine. 

Can you clarify the work done on the other part of the ticket: Identify all places in our code base that use hard-coded stages and statuses so we have a 'hit list' of places to fix and then test, reports, report tabs, filter dropdowns, etc?

**Review by warrensearle — CHANGES_REQUESTED** [review]
Code looks good. Could you try to use the `EXERCISE_STAGE.*` constants rather than 'applied', 'shortlisted' etc being hard-coded in our code?

**Review by NormaJAC — COMMENTED** [review]
I clicked to export the candidate breakdown and diversity but no report was created.
image
image

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC I can see the changes to Diversity and Outreach displays and reports and they look fine.
> 
> Can you clarify the work done on the other part of the ticket: Identify all places in our code base that use hard-coded stages and statuses so we have a 'hit list' of places to fix and then test, reports, report tabs, filter dropdowns, etc?

@nickaddy I have added the hit list to the PR.

**Comment by HalcyonJAC** [comment]
@warrensearle Thank you for the suggestion. I have updated our codebase with constants `EXERCISE_STAGE.*` and `APPLICATION_STATUS.*`. I guess we might need to double-check them after the status V2 is finalised.

**Comment by HalcyonJAC** [comment]
@NormaJAC I have re-deployed the cloud functions and it should work now. Could you test it again, please?

**Review by nickaddy — CHANGES_REQUESTED** [review]
@HalcyonJAC A few observations:

- [x] The last two column headings in dashboard export, diversity report, outreach report still reflect previous stage names
image

- [ ] We have a minor issue with Summary tab on report pages being pushed on to the next row by the longer text, but let’s park that for the time being
- [ ] Filter on Stages tab refers to current statuses, I can’t tell whether hard-coded or dynamic
- [ ] Filter on Stages tab has a tickbox without any named status next to it
image

**Review by Franceswog — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
@nickaddy I have fixed the first and last issue. Could you test them again, please?

**Review by NormaJAC — COMMENTED** [review]
Followed all the instructions, selectable heading is visible in all reports.

**Review by warrensearle — APPROVED** [review]

**Review by nickaddy — APPROVED** [review]
Looks comprehensive, Ryan, thanks.

**Pull request merged**
