### PR TITLE
Feature/2356 Improvements to the Diversity Report

### LINKED ISSUE #2356: Improvements to the Diversity Report
## Background
Following on from the work on a new version of Stages & Statuses, the Diversity report needs iteration to: 1) minimise additional analytical work by correctly capturing the statistics, and 2) expanding the shortlisting tab to include separate breakdowns for sub-tasks where there are multiple shortlisting steps (usually on larger exercises.) 

NOTE: there is an additional request  to automate the calculation of the difference in % points between stages and enable the information to be downloaded in Excel format so that it is compatible with SCC papers and AA reports. It may make sense to get the report fixed first and then conduct that work under a separate ticket, open to suggestions.

## User Story
As a user, I would like additional tabs for sub-tasks in a multiple task shortlisting exercise so that I can see the correct breakdowns for diversity statistics after each task.

## Feature(s) 

- [x] Review and correctly align the new statuses with the appropriate tabs on the Diversity Report
- [x] On exercises where there are multiple shortlisting tasks (i.e. QT, Scenario test and Sift) add additional tabs that capture the statistics for the relevant statuses
- [x] On exercises where there is a single shortlisting task, maintain a single Shortlisted tab
- [x] The gender statistics on the Dashboard need to also be updated in line with the changes to the Diversity Report (see image below) - this could be separated out into an additional ticket

- [ ] The Outreach report also needs to be updated in line with the changes to the Diversity Report (see image below) - this could be separated out into an additional ticket

## Acceptance Criteria (optional/delete if not used)
It's done when the Diversity Report (and other areas identified above) correctly reflect the Diversity statistics and include additional sub-tabs for multiple shortlisting stages.

## User Testing Steps
TBC

## Feature Champion
Nick

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2356

Related PR: [Feature/admin 2356 Improvements to the Diversity Report #1064](https://github.com/jac-uk/digital-platform/pull/1064)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
[Example exercise](https://jac-admin-develop--pr2359-feature-2356-diversi-16e4x23l.web.app/exercise/HbBR4plW5ua2um5jrSeJ/reports/diversity) (Shortlisting methods: QT, Scenario test and Sift)

#### Diversity report
1. Go to the "Diversity" report.
2. Check if there are additional options in the dropdown
    - Qualifying Test(s) Passed
    - Scenario Test Passed
    - Sift Passed
3. Check if the statistics for the relevant statuses appear correctly.

#### Outreach report
1. Go to the "Outreach" report.
2. Check if there are additional options in the dropdown
    - Qualifying Test(s) Passed
    - Scenario Test Passed
    - Sift Passed
3. Check if the statistics for the relevant statuses appear correctly.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:PRODUCTION
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC A few thoughts:

- [The test exercise](https://jac-admin-develop--pr2359-feature-2356-diversi-16e4x23l.web.app/exercise/HbBR4plW5ua2um5jrSeJ/reports/diversity) only has a shortlisting stage so the other tabs should not be included
- On exercises with multiple shortlisting stages, there should not be a separate tab for shortlisting as this will just be a duplicate of the final shortlisting stage
- On exercises with only a single shortlisting stage, it will be some kind of sift; suggest in these cases, there is a single tab 'Sift passed'
- Don't worry about doing anymore work on the dashboard page - we will pick that up us as a separate ticket in the future
- The data does not appear to be accurate, e.g. see below for Applied:



- The data for QT and ST tabs does not appear to be correct, perhaps because this exercise only has a sift
- Suggest once the above fixed, suggest a preview url on Production so that we can examine the tabs with some actual data

**Comment by nickaddy** [comment]
@HalcyonJAC I'd like to better understand how the figures are calculated for the different tabs, perhaps you can clarify? Applied is clear = the total number of applications (excluding draft applications,) I'm not sure about the rest...

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC I'd like to better understand how the figures are calculated for the different tabs, perhaps you can clarify? Applied is clear = the total number of applications (excluding draft applications,) I'm not sure about the rest...

- Shortlisted: the number of applications in Selection Days/SCC/Recommendations stage
- Passed SD: the number of applications in SCC/Recommendations stage
- Recommended to JO: the number of applications in Recommendations stage

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC A few thoughts:
> 
> * [The test exercise](https://jac-admin-develop--pr2359-feature-2356-diversi-16e4x23l.web.app/exercise/HbBR4plW5ua2um5jrSeJ/reports/diversity) only has a shortlisting stage so the other tabs should not be included
> * On exercises with multiple shortlisting stages, there should not be a separate tab for shortlisting as this will just be a duplicate of the final shortlisting stage
> * On exercises with only a single shortlisting stage, it will be some kind of sift; suggest in these cases, there is a single tab 'Sift passed'
> * Don't worry about doing anymore work on the dashboard page - we will pick that up us as a separate ticket in the future
> * The data does not appear to be accurate, e.g. see below for Applied:
> 
> 
> 
> * The data for QT and ST tabs does not appear to be correct, perhaps because this exercise only has a sift
> * Suggest once the above fixed, suggest a preview url on Production so that we can examine the tabs with some actual data

The first three items have been addressed and the `Shortlisted` stage has been removed from the diversity report.

**Comment by nickaddy** [comment]
@HalcyonJAC I've compared a couple of exercises and you can see the results [here](https://miro.com/app/board/uXjVKXTDcjs=/). Can you pls look into the zero return screens boxed in red?

Also, just to be reiterate, exercises with a single shortlisting stage (usually some kind of sift) will still need to have the shortlisted tab including candidates with the status 'Shortlisting passed.'

**Comment by nickaddy** [comment]
@HalcyonJAC @warrensearle I’ve been looking at JAC00133. Overall numbers by stage map precisely, however when you dive into Review/Shortlisting (v1/v2) stage and examine the statuses, there are some anomalies:

- tGAgwrWoRsaMwTMwRbuaEhwkA192 v1 status = Failed First test but has not been given a status in v2 (should be qualifyingTestFailed like the other Failed first test applications)
- YdgFjS1NMNaIW20AnMnTIPexP1R2 and several others v1 status = situationalJudgementFailed but has not been given a status in v2 (should be Situational Judgement Test Failed)
- JDkWYhgeV3UhG2lt5c7w2ri5kD93 and several others v1 status = situationalJudgementPassed but has not been given a status in v2 (should be Situational Judgement Test Passed)

I wonder if the same is true of CAT passed/failed statuses?

The overall breakdown (v1/v2) is:



On the DR itself, the Applied tab is not reflecting the correct application numbers (total 635), and if you compare the other tabs with the numbers under the stages, they are not correct either and the ST passed tab is all blank. Could you take another look pls?

**Comment by HalcyonJAC** [comment]
@nickaddy 
1. I have updated the cloud function to fix the status mappings. 
2. The application number on the Applied tab has been fixed. It seems no application has passed the Scenario Test so the ST passed tab is all blank.

**Comment by nickaddy** [comment]
@HalcyonJAC Overall, 133 is looking correct now, but I still have a few questions -it's essential we get this absolutely right.

1. `No test submitted` (v1 status) is supposed to be mapped to a v2 status `QT not started` - could you pls set this up correctly?
2. `Withdrawn` (v1 status) is supposed to be mapped to a v2 status `Withdrew` - could you pls set this up correctly?
3. If candidates have status `SJ passed`, does that mean that they failed CAT and did not pass shortlisting overall?
4. Why aren't there any candidates with CAT failed? Did every candidate pass the CAT?
5. In your second comment above, do you mean that none of the candidates have Scenario test passed in their status history? We have 240 candidates with ST failed...

If you action the  above, I will test on a few more exercises. Thx for your efforts on this ticket!

**Comment by HalcyonJAC** [comment]
@nickaddy 
1. Sorted
2. Sorted
3. Candidates might have both `SJ Passed` and `CAT Failed` in their status history. We set the pass shortlisting flag by: 
    - Processing v1: move the stage to `Shortlisted`
    - Processing v2: set the status `Shortlisting Passed`
4. There is a candidate (`JAC00133-gwg0274`) with CAT failed in their status history.
5. Yes, I can confirm that none of the candidates have Scenario test passed in their status history.

**Pull request merged**
