### PR TITLE
#1596 Eligibility report pagination

### PR DESCRIPTION
**Pull request by HalcyonJAC**
**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [x] Be proactive in getting your work approved 💪

---
## What's included?
Add pagination items to the bottom of the table. See [JAC Kit #57 Added pagination to bottom of table](https://github.com/jac-uk/jac-kit/pull/57). 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Preview URL: https://jac-admin-develop--pr1605-feature-1596-eligibi-y6h4b37j.web.app

- Make sure you use `@jac-uk/jac-kit` version `0.1.0`
- Open an exercise with eligibility issues in it
- Check pagination functionality 

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

jac-admin-eligibility-issues-pagination

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by HalcyonJAC** [comment]
> I am having some errors on the TABLE on this branch locally. As I still cannot test on the live URL because my email was not part of the system, I will come back to this later.
> 
> image

Hi @lloback, could you run `npm install` to reinstall packages and then test it, please? On this branch I upgraded `@jac-uk/jac-kit` to `0.1.0`.

**Review by andrew-isaac — APPROVED** [review]
Looks good :)

**Comment by HalcyonJAC** [comment]
> Running NPM fixed the issue. Thanks. I don't see the numbers, just `Previous` and `next` buttons:
> 
> image

Hi @lloback, do you use this exercise to do the testing?

https://user-images.githubusercontent.com/79906532/174337851-5e47b830-d70a-4c9b-87ac-0ecb653dd4d6.mov

**Review by tomlovesgithub — APPROVED** [review]
tested locally - again i am a big fan of this feature.

👏

**Pull request merged**
