### PR TITLE
Bugfix: #2108 Table overflow

### LINKED ISSUE #2108: Bugfix: table overflow
When on a small screen or the content is long in a row, the table might overflow and users could not see the last column.

Slack issue: https://judicial-appointments.slack.com/archives/C02QHCFD10C/p1690795765159329

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Add a scrollbar to the Table component if the table is overflowing.

Closes #2108 

Note: this work is related to [jac-kit: Bugfix: #2108 Table overflow](https://github.com/jac-uk/jac-kit/pull/139).

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to the following list and resize the browser window to a small size. Check if you can see all the content in the table.
- Events: https://jac-admin-develop--pr2109-bugfix-2108-table-ov-ds494l0q.web.app/events
- Notifications: https://jac-admin-develop--pr2109-bugfix-2108-table-ov-ds494l0q.web.app/notifications
- Exercises: https://jac-admin-develop--pr2109-bugfix-2108-table-ov-ds494l0q.web.app/exercises
- Candidates: https://jac-admin-develop--pr2109-bugfix-2108-table-ov-ds494l0q.web.app/candidates/
- Applications: https://jac-admin-develop--pr2109-bugfix-2108-table-ov-ds494l0q.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/applied
- Independent Assessments: https://jac-admin-develop--pr2109-bugfix-2108-table-ov-ds494l0q.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/tasks/independent-assessments#notrequested

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/jac-uk/admin/assets/79906532/e24999b1-dd30-4c72-9c87-18783c8dc763

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Review by Franceswog — COMMENTED** [review]
The content in the table are  all present besides Events.

**Comment by nickaddy** [comment]
@HalcyonJAC I can't see any table on the page with the link provided - pls clarify?

**Comment by HalcyonJAC** [comment]
@nickaddy I have updated the links, could you try them again, please?

**Review by nickaddy — APPROVED** [review]
Tables resize accordingly and scroll bar appears if window too small to accommodate all.

**Review by NormaJAC — COMMENTED** [review]
I reduced browser window, I can see all the content in the table as expected

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
