### PR TITLE
#996 Candidate search

### PR DESCRIPTION
**Pull request by warrensearle**
NOTE: once this has been tested and approved before it is merged the following tasks should be addressed:
- [x] Update Table references to use JAC Kit
- [x] Update all references to JAC Kit tableQuery. It has now moved from helpers to Table component

---
## What's included?
Updates tables to use latest version of candidate search, which enables matches on:
 - email
 - application reference number (NOTE: we concentrate on the part after -)
 - candidate name parts (e.g. for "joh" and "sm" will match candidate "John Smith")
 
## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
The following views have been updated. All should now enable improved candidate search:
 - Candidates
 - Applications
 - Review
 - Independent assessments
 - Qualifying test reponses

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
Candidate search by part of name:
image

Application search by reference number:
image

Application search by partial reference number:
image

---
PREVIEW:DEVELOP  _can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by mbrookeswebdev — APPROVED** [review]
💯 👍

**Review by tomlovesgithub — APPROVED** [review]
Great stuff!

**Review by KateMJAC — COMMENTED** [review]
Can I please confirm whether this should be working on the full list below:

- [x] •	Candidates
- [x] •	Applications

The first two functioned as described, however I had issues with the list below:

•	Review - emails weren't recognised and full user names didn't provide a result.
•	Qualifying test responses - full user names didn't provide a result.

**Review by lloback — APPROVED** [review]

**Comment by warrensearle** [comment]
Hi @KateMJAC I have made some changes to the search as follows:
- [ ] Emails can now be searched by the first few letters of the entire email. e.g. "userna" from "username@myemailaddress.com"
- [ ] Emails can now be searched by the first few letters of the domain part (after the @). e.g. "myem" from "username@myemailaddress.com"
- [ ] Fixed (hopefully) the issues you mentioned above. Please let me have examples if you spot and issues

Please could you try again 😄

**Review by HalcyonJAC — CHANGES_REQUESTED** [review]
I've just had a look at this, and I've confirmed that this doesn't necessarily work, but I'm unable to find the cause...

image

On this exercise, looking at `Draft Applications` - a search for one of the candidates works, but the other does not. See Below for a working example, and a non-working example respectively:

image

image

As I said I'm not quite sure what the cause is here but there does appear to be an issue...

**Comment by warrensearle** [comment]
Upon investigating the issue raised by @HalcyonJAC it looks like this is because Candidates are being created without a document in the `candidates` collection. This results in, for now, new candidates being excluded from the search.

Have created ticket [TBC] to capture this bug fix. When it is completed it will resolve the issue of brand new candidates not appearing in the search. I would suggest we progress this PR in the meantime so that all other scenarios can benefit from the search.

**Review by HalcyonJAC — APPROVED** [review]
I will approve then @warrensearle to allow it to progress.

**Review by KateMJAC — COMMENTED** [review]
This is out with the UTG. I will update with feedback once received.

**Review by KateMJAC — CHANGES_REQUESTED** [review]
Hello @warrensearle there is feedback that the search funstion is case sensistive. I tested it myself and it seemed to be the case. 

Is it possible to make it not case sensitive?

**Comment by warrensearle** [comment]
Hi @KateMJAC I have just tested on the preview url and all searches I tried are not case sensitive. See below for the searches I tried. Please can you provide an example(s) where the search appears to be case sensitive:

Candidate search is not case sensitive:
image

Applications search is not case sensitive:
image

QT responses is not case sensitive
image

Stages & status lists are not case sensitive
image

**Review by KateMJAC — APPROVED** [review]

**Pull request merged**
