### PR TITLE
Custom report improvements

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
Logic to display location prefs, part time working prefs and additional working prefs questions in custom report drop down.
Ties in with digital-platform [#740](https://github.com/jac-uk/digital-platform/pull/740).

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Find exercise with additional working preferences.
Navigate to custom report, observe questions are displayed in drop down and on report when it renders.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
image

PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by HalcyonJAC — CHANGES_REQUESTED** [review]
It seems that there's an exception when calling `getApplicationData` cloud function.

Screenshot 2022-08-19 at 15 04 20

Screenshot 2022-08-19 at 15 02 34

**Review by andrew-isaac — APPROVED** [review]

**Review by warrensearle — CHANGES_REQUESTED** [review]
Here is an example configuration for Working Preferences:
image

For the 'Select a column to display' dropdown on the Custom Report, the Working Preferences group of options are not displaying as I'd expect. Is this something you can address?

## Expected

**Working Preferences**
- Location question title
- Jurisdiction question title
- What are your favourite colours (in order of preference)

## Actual
image

**Review by warrensearle — CHANGES_REQUESTED** [review]
Hey @tomlovesgithub sooo close!
Here's how the dropdown looks for my exercise:
image

Note that "What are you favourites colours..." is an additional question I added to **Working Preferences** so I would expect it to appear in that group rather than in the **Welsh** group

**Review by warrensearle — APPROVED** [review]
Great, the issues I spotted are now fixed 😃 
image

**Review by HalcyonJAC — APPROVED** [review]
👍

**Pull request merged**
