### PR TITLE
Remove Back button

### LINKED ISSUE #2549: Remove Back button
## Background
Whenever the Back button is clicked on an exercise Dashboard page - irrespective of the page the user is on - the user is taken to the Exercise Set-up Overview page. The button is misleading and would be best removed.

## Feature(s) Description
- [ ] Remove the Back button from all pages

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Internal testing only

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
closes #2549 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to link: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/exercise/umjxBon2GRlc6rshqEfG/details/overview
    - Check all edit page of each section on the exercise set-up menu, the back button should be removed.
  
Screenshot 2024-09-02 at 11 38 55
Screenshot 2024-09-02 at 11 57 22

- Go to link: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/exercise/umjxBon2GRlc6rshqEfG/stages/scc
  - Check all set status and set back pages of each stage on stages menu, the back button should be removed.
Screenshot 2024-09-02 at 11 40 30

- Go to: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/exercise/umjxBon2GRlc6rshqEfG/reports/sift
  - Check panels of sift and selection day on report menu, the back button should be removed.
Screenshot 2024-09-02 at 11 43 01

- Go to: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/panellists
  - Check individual panellist page, the back button should be removed.
Screenshot 2024-09-02 at 11 44 10

- Go to: https://jac-admin-develop--pr2553-feature-2549-remove-qh3pytzu.web.app/exercise/6Wv5VBkhyIGeZzvqURjQ/externals
  - Check external external exercise edit  summary page.
Screenshot 2024-09-02 at 11 55 11

Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@KoWeiJAC There is a lot of space wastage on the screen - is it possible to reduce the gaps on these pages (circled in the screenshot?)
image

**Comment by KoWeiJAC** [comment]
> @KoWeiJAC There is a lot of space wastage on the screen - is it possible to reduce the gaps on these pages (circled in the screenshot?) image

Hi @nickaddy,

The spaces have been reduced, could you check it again to see if it is ok? Thanks
Screenshot 2024-09-02 at 12 44 40

**Review by nickaddy — APPROVED** [review]
Looks much better, @KoWeiJAC, thx!

**Review by NormaJAC — APPROVED** [review]
Tested

**Review by Franceswog — APPROVED** [review]

**Review by HalcyonJAC — APPROVED** [review]

**Pull request merged**
