### PR TITLE
Feature/2518 Add additional Gantt chart filter

### LINKED ISSUE #2518: Add additional Gantt chart filter
## Background
PO would like to add the option to filter by exercise activity.

## User Story
As an Admin, I would like to be able to filter the GC view by activity so that I can see periods of heavy activity for, e.g. QTs.

## Feature(s) Description
- [x] Add an additional exercise activity filter that includes only the exercise activities displayed on the GC

## Acceptance Criteria 
Admins can filter the GC by exercise activities and be able to see, e.g. only QTs.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2518 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Preview URL:
- [Dev](https://jac-admin-develop--pr2527-feature-2518-add-add-06a0opu6.web.app/exercises/programme-view)
- [Production](https://jac-apply-admin-production--pr2527-feature-2518-add-ad-jqiiz8cv.web.app/exercises/programme-view)

Steps:
1. Go to the Programme view of an exercise.
2. Check if the activity filter works correctly.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

Demo:

[video-30145429-60645221a89feaa0ddd1681dd7928732.webm](https://github.com/user-attachments/assets/9c6fec83-f219-40dc-bd83-012e10431237)

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
👍

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC This is going to be very useful, however, SD option is not working, I'm not sure why...

**Comment by HalcyonJAC** [comment]
@nickaddy Thank you for spotting that. I have fixed the SD option. Could you refresh the page and test it again, please?

**Review by nickaddy — APPROVED** [review]
@HalcyonJAC Great job, thx!

**Pull request merged**
