### PR TITLE
#1314/additonal legal experience

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
Added a section under each item within legal experience containing `judicial-functions` which allows collected details to be displayed to admins. 

*Ive added some `<hr>` tags to add lines between items, this data is quite deeply nested and i felt the UI needed some separations*

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Find an 'legal' exercise 
image
- Ensure an application has been made to this exercise, which has selected 'The carrying-out of judicial functions of any court or tribunal' under 'Post-qualification experience'. (apply side)
image
- Observe that the information entered is displayed on the admin portal.
image

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
image

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by lloback — DISMISSED** [review]
Probably related to the APPLY but the values are empty:
image

Please link this PR to the one in the APPLY side.

**Review by HalcyonJAC — APPROVED** [review]
Looks good to me

**Comment by joy-ade** [comment]
@tomlovesgithub There is an updated for this ticket, l will be providing the information at some point next week.

**Comment by joy-ade** [comment]
@tomlovesgithub There has been an updated to the the way captured below question  find the below for your information.
 
Legal Experience:
Date:
Categories of Law:
Time engaged in this activity: Fulltime/part time if part time how many days in a week
Judicial offices:
Are you a Magistrate/Have you ever been a Magistrate Yes/No
Date year.
Current/previous Judicial Roles:
Judicial Appointments:
Dates:
Nature of Appointments:
Circuit or Region:
Jurisdiction:
Tribunal:

**Review by mbrookeswebdev — APPROVED** [review]

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
@tomlovesgithub Can you please remove the code that is not part of this PR.

**Review by mbrookeswebdev — APPROVED** [review]
👍

**Review by warrensearle — APPROVED** [review]
Code change looks good to me 👍

**Comment by tomlovesgithub** [comment]
Updates to wording see ticket

**Review by KateMJAC — COMMENTED** [review]
Sent to UTG 27/07 to review final changes

**Comment by KateMJAC** [comment]
This has been sent to UTG today after most recent changes were made.

**Review by KateMJAC — COMMENTED** [review]
This has been sent to UTG today after most recent changes were made.

**Pull request merged**
