### PR TITLE
Feature/2230 Character declaration updates

### LINKED ISSUE #2230: Character declaration updates
**Background**
At the digital meeting on 28/11/2023, updates to the character declaration were discussed. The overall functionality is not working and needs to be fixed before we can reengage with users on this feature.

**Feature(s) Description** 

- Reword 'Recommendation' to: **Recommended SCC approach**.

- Force Character issues from the current exercise to be visible onscreen in the default view; at the moment they are not being displayed

- Reword ‘View all issues’ to **_View all character issues from previous applications_**

· Fix recommendation dropdown so that selected option remains onscreen when chosen, it currently remains blank when the an option is selected.

- Fix offence category dropdown so that selected option remains onscreen when chosen,  it currently remains blank when the an option is selected.

- Fix search functionality of search box and add guidance on what can be searched as per other search functionality on Admin

- Where no declaration provided on previous exercises due to the candidate not having been selected and the data not requested, the platform should add **Data not requested** next to each exercise that the candidate has applied for where there is no entry 

- Send the download to the desktop, not a mysterious location on Google drive!

**Ticket Champion**
Digital team

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2230 

- [x] Reword 'Recommendation' to: **Recommended SCC approach**.
- [x] Force Character issues from the current exercise to be visible onscreen in the default view; at the moment they are not being displayed
- [x] Reword ‘View all issues’ to **_View all character issues from previous applications_**
- [x] Fix recommendation dropdown so that selected option remains onscreen when chosen, it currently remains blank when the an option is selected.
- [x] Fix offence category dropdown so that selected option remains onscreen when chosen,  it currently remains blank when the an option is selected.
- [x] Fix search functionality of search box and add guidance on what can be searched as per other search functionality on Admin
- [x] Where no declaration provided on previous exercises due to the candidate not having been selected and the data not requested, the platform should add **Data not requested** next to each exercise that the candidate has applied for where there is no entry 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link: https://jac-admin-develop--pr2278-feature-2230-charact-dzyc1799.web.app/exercise/aDxEqK36807d0Nhpugo3/reports/character-issues
- Click `Refresh` to generate latest report
- `Recommended SCC Approach Field`
    - Locate the "Recommended SCC Approach" field (refer to place 1 in the image).
    - Confirm that this field is visible for each candidate.
- Selected Option in `Recommended SCC Approach Field`
    - Check the "Recommended SCC Approach" field for each candidate.
    Verify that the selected option is displayed in this field (refer to place 2 in the image).
- `View All Character Issues` Link
    - Look for the "View all character issues from previous applications" link (refer to place 3 in the image).
    - Ensure that this link is visible for each candidate.
- Selected Option in `Offence Category` Field
    - Check the "Offence Category" field for each candidate.
    - Confirm that the selected option is displayed in this field (refer to place 4 in the image).  
image
- Check the `Search application records` functionality
    - Click `Help`, it should appear searchable fields:
image
    - Enter a least 3 letters, it should filter the conditates accordingly.
image
- Go to the preview link: https://jac-admin-develop--pr2278-feature-2230-charact-dzyc1799.web.app/exercise/7LgaEMudSSfBC1fOwnaf/reports/character-issues
   - Click `Refresh` to generate latest report
    - Click `View all character issues from previous applications` of the candidtate `application-0012 Jac`
    - If the candidate not having previous applications, it should appear `No previous applications with character issues `
image
    - Click `View all character issues from previous applications` of the candidtate `application-0001 Jac`
    - If the candidate has character issues in previous exercise, it should list the issues.
    image
    - If the candidate not having been selected and the data not requested, it should show `Data not requested` in exercise.
image

    

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by KoWeiJAC** [comment]
@nickaddy 

There's a technical limitation on filtering 'All' applications, which is to exclude 'withdrawn applications'.
When the 'All' filter comes with search, it won't work properly. (Firebase will report error and ask us to add indecies for all of keywords for seaching, which is not feasible)
Screenshot 2024-01-16 at 10 45 46
Screenshot 2024-01-16 at 10 46 12

There are 2 ways that may be help:
1. If filtering with 'All', we list all applications including 'withdrawn applications'.
2. Remove the 'All' option from filters, user can only filter with specific application status.

Could you help me to confirm which way is ok, or there may be other way that we can solve this issue.

Thanks.

**Review by NormaJAC — COMMENTED** [review]
Worked as expected, I struggled to understand some of the instructions. Could be a bit clearer i.e. _'For each conidate' 
'It should appear Recommended SCC approach field(place 1 in the image below).'_

**Comment by KoWeiJAC** [comment]
> It should appear Recommended SCC approach field(place 1 in the image below).

**Comment by HalcyonJAC** [comment]
> Worked as expected, I struggled to understand some of the instructions. Could be a bit clearer i.e. _'For each conidate' 'It should appear Recommended SCC approach field(place 1 in the image below).'_

@NormaJAC 
Thank you for your test and suggestion.
I've update the instructions. Could you help me to take a look, to see if it's clearer ?
Thanks!

**Comment by NormaJAC** [comment]
@HalcyonJAC  yes, the instructions are clearer thanks

**Review by NormaJAC — APPROVED** [review]
Looks good to go.

**Comment by nickaddy** [comment]
@warrensearle I'm not 100% clear on the purpose of these dropdowns at the top and how the SETs would use them. Also, shouldn't they have descriptions next to them?



The top dropdown looks like a Stage selection, the second a Status selection. Would these be used only when SETs are reviewing applicants later? See the error above as to why All is not appearing as an option in the top menu.

**Comment by warrensearle** [comment]
@nickaddy I am not clear either but yes they are stage & status dropdowns and they filter the results shown below. Yes, better labeling is a good shout :+1:
@HalcyonJAC and @JeremykJAC as you built this report and are closer to the motivations behind it could you help answer Nick and @KoWeiJAC questions :smile:

**Comment by KoWeiJAC** [comment]
@warrensearle  Yes, they are stage  & status dropdowns for filtering. Thanks.

@nickaddy , I've discussed with Ryan, this report has been for a while (2021) https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/1351. We haven't work on it before. So, we're not sure about the motivation.
But, I think it's good to add label to them as well, it would be clearer.

**Review by warrensearle — APPROVED** [review]
Code looks good to me 👍

**Comment by KoWeiJAC** [comment]
@nickaddy I've added labels for the dropdowns.
Could you help me to confirm if it's ok ?
Thanks!

**Review by tomlovesgithub — APPROVED** [review]

**Review by drieJAC — CHANGES_REQUESTED** [review]
I notice that the action button never seems to resolve on page load. I've added a video below. The network tab shows all of the requests have completed. Not sure if this is anything to do with your code but maybe worth a look.

https://github.com/jac-uk/admin/assets/115651787/4904f1d5-e5d4-4887-87c8-c1f5c7bcf67f

**Review by Franceswog — COMMENTED** [review]
The refresh button changes to 'Error' hence nothing is been uploaded.

**Comment by HalcyonJAC** [comment]
> I notice that the action button never seems to resolve on page load. I've added a video below. The network tab shows all of the requests have completed. Not sure if this is anything to do with your code but maybe worth a look.
> 
>  Screen.Recording.2024-01-23.at.15.19.53.mov

Thank you for finding this issue, it seems that if there's no applications in the report, it shows the loading UI.
I've changed the UI, when there's no applications in the report, it will display as following:
image
It can be test this on this exercise:
https://jac-admin-develop--pr2278-feature-2230-charact-dzyc1799.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/reports/character-issues

**Comment by HalcyonJAC** [comment]
> The refresh button changes to 'Error' hence nothing is been uploaded.



> The refresh button changes to 'Error' hence nothing is been uploaded.

@Franceswog 
Thank you for report this issue,
I've updated the the backend and fixed this issue,
Could you help me to check it again ?

Thanks

**Review by NormaJAC — COMMENTED** [review]
I've followed all the top instruction, they seem to work as expected.

**Review by nickaddy — CHANGES_REQUESTED** [review]
Great progress :-) Can you pls look at these issues I discovered when I tested this morning:

-	It is not possible to type into **_Reason for Recommendation_** field
-	When clicked, **_Generate report_** button changes to **_Error_** however report is generated correctly

**Comment by KoWeiJAC** [comment]
> Great progress :-) Can you pls look at these issues I discovered when I tested this morning:
> 
> * It is not possible to type into **_Reason for Recommendation_** field
> * When clicked, **_Generate report_** button changes to **_Error_** however report is generated correctly

@nickaddy  
Thank you for finding these 2 bugs.
I've has some change to fix them.
Could you help me to test it again ?
Thanks

**Review by nickaddy — APPROVED** [review]
Looking good, Ko Wei!

**Review by tomlovesgithub — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
👍

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
