### PR TITLE
Feature/2406 Generate basic programme Gantt chart view

### LINKED ISSUE #2406: Generate basic programme Gantt chart view
## Background
Matt and Programme Office (PO) would like to have a 'live' programme view across all exercises on the Digital Platform.

## User Story
As PO, I would like to have a 'live' Gantt chart view across the entire programme so that I can easily view resource bottlenecks, QT clashes and other useful information quickly and easily.

## Benefit(s) to user (if not already clear from User story)
- Allows easy viewing of all/multiple exercise timelines
- Allows programme view filtered by, e.g. exercise type, team, for resource considerations etc
- Allows easy viewing of, e.g. QT clashes
- Provides up to date view according to 'live' dates in Admin
- Potentially replaces Programme Live spreadsheet

## Feature(s) Description
[Miro discussion board](https://miro.com/app/board/uXjVKE47RsE=)

- [x] Create a Gantt chart view of the exercise programme 

- [x] The top row of the chart must be always visible onscreen, i.e. when you scroll down the page it remains in place, however it is possible to scroll left and right
- [x] The top row displays a 6-month period starting from one month in the past and continuing to 5 months in the future (default view)
- [x] It is possible to scroll to the left (the past) as far back as the opening date of the oldest live exercise
- [x] It is possible to scroll to the right (the future) as far forward as the final outcome to candidates date of the latest live exercise
- [x] Below the timeline row, each live exercise has its own row with the first column being the exercise reference number 
- [x] The reference number column should also be locked on screen, i.e. you can scroll left or right, but the reference column remains in place
- [x] On hover over the exercise reference, the name of the exercise appears
- [x] On each row, a sequential list of activities appears, each in a separate lozenge
- [x] The length of the lozenge aligns with the start and end dates of the activity
- [x] One-day events, e.g. Eligibility SCC, are shown as a line
- [x] On hover over the line, the name of the activity appears
- [x] The default sort of exercises is by launch date
- [x] Activities use the same terminology as the timeline but we might want to rephrase the titles of some activities if they are too long to fit in the box
- [x] When you hover over the activity, the full title and the start and end dates appear
- [x] The activities to be included on each timeline are shown below, along with their colour-coding

## Acceptance Criteria 
It's done when the above criteria are met.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Matt, Gemma and Adela only
Interact with the Gannt chart and share any observations where it falls short of requirements.

## Feature Champion
Matt (Gemma/Adela)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2406

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Preview link: 
- [Dev](https://jac-admin-develop--pr2489-feature-2406-generat-f95knc96.web.app/exercises/programme-view)
- [Production](https://jac-apply-admin-production--pr2489-feature-2406-genera-hhn13a0p.web.app/exercises/programme-view)

Steps:
- Ensure the top row is always visible onscreen.
- Ensure the top row displays a 6-month period starting from one month in the past and continuing to 5 months in the future (default view).
- Ensure to scroll to the left (the past) as far back as the opening date of the oldest live exercise.
- Ensure to scroll to the right (the future) as far forward as the final outcome to candidates date of the latest live exercise.
- Below the timeline row, ensure each live exercise has its own row with the first column being the exercise reference number.
- Ensure the reference number column should also be locked onscreen.
- On hovering over the exercise reference, ensure the name of the exercise appears.
- On each row, ensure a sequential list of activities appears, each in a separate lozenge.
- Ensure the length of the lozenge aligns with the start and end dates of the activity.
- Ensure one-day events, e.g. Eligibility SCC, are shown as a line.
- On hover over the line, ensure the name of the activity appears.
- Ensure the default sort of exercises is by launch date.
- When you hover over the activity, ensure the full title and the start and end dates appear.
- Ensure the activities to be included on each timeline are shown below, along with their colour-coding.

    image

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/user-attachments/assets/0f8f4f89-67f2-4819-905c-c26e17f8714c

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC Thx for your work on this. Can you pls make two amends that will really support internal testing?

1. Amend the launch to close item - it should only cover the dates between when the application window opens and closes - usually about 2-4 weeks at the start of the exercise.
2. Create a preview url on production so that we can see how it looks with live data.

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC Thx for your work on this. Can you pls make two amends that will really support internal testing?
> 
> 1. Amend the launch to close item - it should only cover the dates between when the application window opens and closes - usually about 2-4 weeks at the start of the exercise.
> 2. Create a preview url on production so that we can see how it looks with live data.

@nickaddy 
1. I guess it's because the configuration (e.g. open date, close date) of some exercises on Dev is not quite clean and correct.
2. Here is the [preview URL](https://jac-apply-admin-production--pr2489-feature-2406-genera-hhn13a0p.web.app/) on Production.

**Comment by nickaddy** [comment]
Chrs @HalcyonJAC. How do I navigate to the GC from the preview url?

**Comment by HalcyonJAC** [comment]
@nickaddy It's in the submenu of exercises.

image

**Review by NormaJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC The feedback from PO has been really positive 👍 Could you pls action the following points?

- Add a full screen button to the page
- Amend the link text under Exercises to 'Programme view' and have it appear under 'Archived exercises'
- Explore the following: is it possible to hide the scroll bar and then navigate up/down/left/right by moving mouse whilst clicking and holding?

I had one other thought about whether we should add a colour key but that could be in a future iteration.

**Review by Franceswog — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
@nickaddy 
1. A Full-screen button has been added.
2. The link text has been amended.
3. I can hide the scrollbar but it will look like below. Is it okay?

    image

**Comment by nickaddy** [comment]
@HalcyonJAC Now you have added the control panel, I think it's fine as it is. Happy for you to merge and close and we can release on Monday :-)

**Review by tomlovesgithub — APPROVED** [review]
wow

**Pull request merged**
