### PR TITLE
Events (display logged events)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## What's included?
A new Events page has been added. 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

You can access it via a link on the top-right of the screen.

image

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by mbrookeswebdev — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
Looks good to me 👍 
(I like the json pretty)

**Review by tomlovesgithub — APPROVED** [review]
love it, perhaps we want to consider rolling this out for digital only initially.

I remember when you showed us this adding an event log was very straightforward, could we perhaps get a few lines of dev documentation on how to use it?

**Comment by mbrookeswebdev** [comment]
@HalcyonJAC, I've re-generated the preview url as it expired to help Kate test the Events page and [noticed this error came up on Sentry](https://sentry.io/organizations/judicial-appointments-commissi/issues/2373267414/?project=1792541&referrer=slack). 

Also, I believe currently the Events page is visible to everyone, so we need to hide  it similar to QT reset button, so only Digital can see it.

**Review by KateMJAC — CHANGES_REQUESTED** [review]
Hello @HalcyonJAC, I like the position of the 'Event' link, the only thing is that we don't want all admin users to be able to see and access this feature. 

Is it possible that only certain people have access? including Maria, Tom, Joy, myself, Warren and a Halcyon representative.

**Review by KateMJAC — COMMENTED** [review]
@HalcyonJAC following my previous question, I wanted to know if it was possible to add the logging of changes to personal details and application questions on admin?

**Review by KateMJAC — COMMENTED** [review]
@HalcyonJAC following a few comments above, are we able to make this a Super Admin only feature?

**Comment by HalcyonJAC** [comment]
>  following my previous question, I wanted to know if it was possible to add the logging of changes to personal details and application questions on admin?

Hi @KateMJAC 

There is a related ticket in ZenHub to do exactly that, which is currently in progress (mostly complete though)... https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/jac-uk/admin/1307

**Comment by HalcyonJAC** [comment]
> following a few comments above, are we able to make this a Super Admin only feature?

I don't see why not. Leave it with me...

**Comment by HalcyonJAC** [comment]
@KateMJAC - quick update on the above...

- I have made the code change so that the Events link only appears for super admins. 
- I also added Halcyon to the list of super admins so we can assist in testing and systems support of this feature. 

For reference the list of super admins in the system is the following:

```js
const authorisedUsers = [
  'maria.brookes@judicialappointments.digital',
  'warren.searle@judicialappointments.digital',
  'tom.russell@judicialappointments.digital',
  'kate.malone@judicialappointments.digital',
  'joy.adeagbo@judicialappointments.digital',
  'halcyon@judicialappointments.digital',
];
```

Note: I added halcyon, the rest of the list was already there.

**Comment by joy-ade** [comment]
@HalcyonJAC looks good to me

**Comment by HalcyonJAC** [comment]
@joy-ade If you have reviewed this and are happy with it can you approve the Pull Request please?

**Pull request merged**
