### PR TITLE
eligibility issues - renamed filename

### PR DESCRIPTION
**Pull request by HalcyonJAC**
**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Export the Eligibility Report. The filename should no longer be called `Contacts.xlsx`

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by lloback** [comment]
image

The name is indeed different from `Contacts.xls`

**Review by lloback — APPROVED** [review]
As a feedback, when creating a PR you should follow the instructions, like, please add a task number, steps to reproduce, and delete the things that doesn't apply to your PR. If you don't agree with the guidelines, please raise the issue and I am sure they will help you and deal with the issue.

**Review by mbrookeswebdev — APPROVED** [review]
👍

**Review by joy-ade — APPROVED** [review]
Approved by product team and UTG

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
