### PR TITLE
update application to use new editablefields

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?

Updated the application view to use new versions of the `EditableField` component.
Citizenship†, Reasonable adjustments†, and Reasonable adjustments details* have can now be updated by admins.
† new dropdown selection type
* textfield
 
## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- View any application to any exercise.
- under personal details you should see that Citizenship, Reasonable adjustments, and Reasonable adjustments details can now be updated.
- Make changes
- Save
- Reload page, changes persist

[bonus round] - Check info changes on apply portal too

## Risk - how likely is this to impact other areas?
🟢 Low risk - this is a self-contained piece of work

## Additional context

image
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by KateMJAC** [comment]
Note for Kate and Joy. This PR can't be tested until #24 is pushed.

**Review by HalcyonJAC — APPROVED** [review]
This does work if you change, but it doesn't prepopulate the yes/no field for the reasonable adjustments dropdown (picky I know  - I'll approve but worth noting...).

image

To reiterate - it *does* save correctly though.

Also checked the apply portal and it seems to work there too :)

**Review by mbrookeswebdev — APPROVED** [review]
👍  as @HalcyonJAC mentioned, Yes/No doesn't pre-populate, but it saves in the database and displays correctly on Apply.

**Comment by joy-ade** [comment]
@tomlovesgithub I tested and its works. Gone out UTG

**Review by joy-ade — APPROVED** [review]
Approved by product Team and UTG

**Review by lloback — APPROVED** [review]
✔︎

**Pull request merged**
