### PR TITLE
Feature/2124 eligibility and character excel downloads

### LINKED ISSUE #2124: Eligibility and character Excel downloads
**Issue Title**
Eligibility and character Excel downloads

**[History/context]**
At present, each declaration made by a candidate concerning eligibility and character is included in a single cell on the excel download. This makes the information more difficult for teams to search through. We should look to extract the data so that each declaration shows in a separate row. Admin users would like to see each application form declaration entry in a separate row on an Excel download. Would like to see it exactly as it is on the application form, a row for each question (e.g. Qualification entries should be in separate rows from Post qualification experience, a barrister can be exempt from pupillage - have it as a row stating that they are exempt and have uploaded an exemption certificate.)

**USER STORY** 
As an admin, I want each candidate eligibility and character declaration entry to be in a separate cell on an Excel download so that I can extract the data exactly as it is on the application form. 

**[Acceptance Criteria]** 
Each declaration entry to be in a separate cell on an Excel download

**[User Testing Steps]**
Go to an exercise page, click on reports, click on character issues, click on generate report, click on export to Excel.
Check that all the declaration entries are in separate cells on the Excel download.

**[Ticket Champion]**
Roadmap item.

**[Screenshots / wireframes / designs / pictures]**
**"As is"**
Character download
image

Eligibility download
image

**"To be"**
Character check - column M, O, AH and AI (Character information, Professional background, Qualifications and Post qualification experience)
image

image

image

Eligibility issues - column J and K (Qualifications and Post qualification experience)

image

image
**[Happy Story**
To be able to see each declaration entry in separate cell which allows admins to save time when extracting data. 

**[Sad story]** 
 Admins have to spend time copying and pasting data from one cell into separate cells.

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2124

Note: This PR is related to [digital-platform: Feature/admin-2124 eligibility and character reports](https://github.com/jac-uk/digital-platform/pull/942).

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

**Character issues report**
Example exercise: https://jac-admin-develop--pr2145-feature-2124-eligibi-hgpxxyka.web.app/exercise/ZutEH7OHcjRlUIfXLyqP/reports/character-issues

1. Go to the "Character Issues" report.
2. Click "Export to Excel" button to download the report file.
3. Open the file and check if the data of `Character information`, `Professional background`, `Qualifications` and `Post qualification experience` are in separate cells.

**Eligibility issues report**
Example exercise: https://jac-admin-develop--pr2145-feature-2124-eligibi-hgpxxyka.web.app/exercise/ZutEH7OHcjRlUIfXLyqP/reports/eligibility-issues

1. Go to the "Character Issues" report.
2. Click "Export to Excel" button to download the report file.
3. Open the file and check if the data of `Qualifications` and `Post qualification experience` are in separate cells.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

Screenshots:

- Character information

    Screenshot 2023-09-26 at 09 11 33

- Professional background

    Screenshot 2023-09-26 at 09 12 02

- Qualifications and Post qualification experience

    Screenshot 2023-09-26 at 09 13 05

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by Franceswog — COMMENTED** [review]
Character and Eligibility issues report both downloaded and exported to excel with post qualification and qualification data in separate  cells.

**Review by nickaddy — CHANGES_REQUESTED** [review]
•	Character date format not working correctly, e.g. Candidate Dewey Schowalter, 3rd PQWE dates are December 2009 - October 2014 but displays as "2009-12-01 - Director  at fake business name"
•	We ask candidates for month and year format – this should be reproduced in the download file and include start and finish dates, i.e in this case December 2009 - October 2014, perhaps the format could be MMM-YYYY – MMM-YYYY to make it a bit shorter?
•	Also in 1st PQE missing space between date and location

**Review by warrensearle — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC **Should I still be using these links to test?**

Character issues report
Example exercise: https://jac-admin-develop--pr2145-feature-2124-eligibi-hgpxxyka.web.app/exercise/ZutEH7OHcjRlUIfXLyqP/reports/character-issues

Eligibility issues report
Example exercise: https://jac-admin-develop--pr2145-feature-2124-eligibi-hgpxxyka.web.app/exercise/ZutEH7OHcjRlUIfXLyqP/reports/eligibility-issues

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC **Should I still be using these links to test?**
> 
> Character issues report Example exercise: https://jac-admin-develop--pr2145-feature-2124-eligibi-hgpxxyka.web.app/exercise/ZutEH7OHcjRlUIfXLyqP/reports/character-issues
> 
> Eligibility issues report Example exercise: https://jac-admin-develop--pr2145-feature-2124-eligibi-hgpxxyka.web.app/exercise/ZutEH7OHcjRlUIfXLyqP/reports/eligibility-issues

Yes, please.

1. The date format has been fixed.

    - If there is an end date: `01-2009 - Ongoing Fee paid Tribunal Judge at fake business name`
    - If there is no end date: `01-2009 - 01-2014 Director at fake business name`

2. The space has been added in the PQE.

**Review by nickaddy — CHANGES_REQUESTED** [review]
Sorry, Ryan, there are still issues with the excel downloads. Can you address the following pls?

1. Date of birth is showing in US format - pls change to UK format: DD/MM/YYYY (column I in both downloads)
2. 1st qualification (Col AK in character download) is showing in US format - pls change to UK format: DD/MM/YYYY (should be the same setting for 2nd qualification too)
3. Post-qualification work experience (Character - col AM onwards, Eligibility col L onwards) - whatever the month in the candidate application, the spreadsheet is returning 01 for every month, e.g. Apr 2019 is 01-2019 etc. Pls fix this and change the format to MMM YYYY - MMM YYYY, e.g. APR 2009 - NOV 2009.

Many thanks.

**Review by nickaddy — APPROVED** [review]
Thank you for your persistence with this, Ryan, it was worth it - it looks great! This has already been through UT so happy for this to be merged now, assuming code review complete :-)

**Pull request merged**
