### PR TITLE
#932 Download qualifying test report

### PR DESCRIPTION
**Pull request by warrensearle**
Also includes drilling down into each score

### CODE REVIEW

**Review by lloback — CHANGES_REQUESTED** [review]
[Vue warn]: Error in render: "TypeError: Cannot read property 'female' of undefined"

**Comment by lloback** [comment]
I don't kno if this is expected, but the percentage is NaN
image

**Comment by warrensearle** [comment]
@lloback I've removed old data from our develop database, which was responsible for the issues experienced above.

**Review by lloback — APPROVED** [review]
all good.

**Pull request merged**
