### PR TITLE
#1901 Reasonable Adjustments - Additions to ticket 1842

### LINKED ISSUE #1901: Reasonable Adjustments - Additions to ticket 1842
Related to ticket 1842 - Additional Items to be added

Can the following additions be added to this feature:

- [x] Under the Status can `Scenario Test` be added as an option in the drop down.

- [x] On the candidates name where they select a status and reason from the drop down could a link called `add another` to enable them to add another status and reason - some candidates will have an RA for a QT and a SD, so will need to reasons recorded.

- [x] Can a free text box be added underneath `Where the reasonable adjustments was given` for admin to record any extra time or % of time given - This will need to be saved and recorded against the candidate like the other information and should only appear once an option has been selected in the drop downs.

- [x] On the `Export Data` spreadsheet could the most recent Reasonable adjustment for the candidate be pulled from the platform and shown in the spreadsheet with all the information - If not possible we can look at later on.

- [x] In the RA history can the `Where the reasonable adjustments was given` and also any comments entered in the free text box be visible to the team - if it is a lot of information, happy for a `view all` link to be used.

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #1901 

- [x] Add `Scenario Test` to the `Where the reasonable adjustments was given` drop-down.
- [x] Add a button `Add another` to add another status and reason.
- [x] Add a text box underneath `Where the reasonable adjustments was given` for admin to record any extra time or % of the time given.
- [x] Export the most recent Reasonable adjustment for the candidate and show it in the spreadsheet.
- [x] Show status, reason, and note in the RA history.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Go to Reasonable Adjustments Report and check if the above items work.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://user-images.githubusercontent.com/79906532/220909375-fcb027ea-6a26-4700-b94e-0f4d2d0c450e.mov

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP

### CODE REVIEW

**Review by tomlovesgithub — APPROVED** [review]

**Comment by warrensearle** [comment]
Hey @andrew-isaac can you double check one of the requirements in this ticket please: is this really meant to add 'Scenario Test' as an option in the 'Status' dropdown? Wouldn't adding 'Scenario Test' as an option under 'Where the reasonable adjustment was given' make more sense?

**Review by warrensearle — COMMENTED** [review]
Code looks fine, just a question about the requirement (see my earlier comment)

**Comment by andrew-isaac** [comment]
@warrensearle  thank you for spotting my stupid mistake! The ST bit should be under where the adjustment was given - the other drop down :)

Ryan can you amend it please?

**Review by andrew-isaac — CHANGES_REQUESTED** [review]
@warrensearle  thank you for spotting my stupid mistake! The ST bit should be under where the adjustment was given - the other drop down :)

Ryan can you amend it please? Sorry it is my fault!

**Review by andrew-isaac — APPROVED** [review]

**Pull request merged**
