### PR TITLE
#926 Barrister eligibility

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
* Add `Date called to the Bar` information under application qualifications section.
* Change `Has not completed pupillage` to `Has completed pupillage`.

Note: This PR is related to [apply #926 Barrister eligibility](https://github.com/jac-uk/apply/pull/927) and [jac-kit Add qualification constants and filters](https://github.com/jac-uk/jac-kit/pull/77). The version of `@jac-uk/jac-kit` will upgrade to `0.1.8`.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
1. Go to Application Qualifications section.
2. Check if you can edit "Date called to the Bar", "Has completed pupillage", "Date completed pupillage", "Did not complete pupillage notes".

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://user-images.githubusercontent.com/79906532/205704088-d3294f27-e05b-4d1f-89e4-1977eec1be96.mov

## Related permissions
- No permission changes required

---
PREVIEW:DEVELOP

### CODE REVIEW

**Comment by HalcyonJAC** [comment]
> image
> 
> I can't edit. Used the same user as your video https://jac-admin-develop--pr1745-feature-926-barriste-sscfl75t.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/applications/draft/application/E7FgAgArIywGf27iKn1K

Hi @lloback, could you see the "Change" button after you click "Edit" at the top of the application?

**Review by andrew-isaac — CHANGES_REQUESTED** [review]
When I tested a few applications I was able to edit the data for `Date called to the Bar` question but when I hit save the date was not saved and just stayed blank

**Comment by HalcyonJAC** [comment]
> When I tested a few applications I was able to edit the data for `Date called to the Bar` question but when I hit save the date was not saved and just stayed blank

Hi @andrew-isaac, I've fixed the bugs. Could you try again, please?

**Review by andrew-isaac — CHANGES_REQUESTED** [review]
@HalcyonJAC  - The date worked for me this time but on the admin side when I edit the fields and select `No` for completed pupillage I am not given the questions to add it - it asks me for the date still. If select No on the admin side, editing an application I should get the same options as on apply. 

image

**Review by andrew-isaac — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
👍

**Review by warrensearle — APPROVED** [review]
👍

**Review by warrensearle — APPROVED** [review]

**Pull request merged**
