### PR TITLE
#963 Add optional text area to questions for Scenario test for instru…

### PR DESCRIPTION
**Pull request by lloback**
image

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
Looks good 👍 
(only question is whether hint is the right name for this)

**Comment by lloback** [comment]
It needs to be, because it is replacing the HINT line "Answer below:"

**Comment by warrensearle** [comment]
Is it? I thought it was optional and in addition to the existing 'Answer below:' hint. Please check with @Rebecca-mcknight1991

**Comment by lloback** [comment]
> Is it? I thought it was optional and in addition to the existing 'Answer below:' hint. Please check with @Rebecca-mcknight1991

I thought the same, but then, when I looked into the code, There was no place to add it as it was heavily embedded on the  TEXTINPUTAREA ...

**Pull request merged**
