### PR TITLE
#2159 Disallow archiving until exercise unpublished from website

### LINKED ISSUE #2159: Remove exercises from website when archiving
**Background**
Rob noticed that when you archive an exercise, if you haven't clicked 'remove from apply website,' the exercise remains on there and then there is no option to remove it, except to unarchive and then remove it. 

**User Story** 
As an admin, I would like exercises to be removed from the website when they are archived so that they are no longer visible to end users.

**Feature(s) Description** 
When the selection exercise team go to archive an exercise, the platform will automatically unpublish live information pages from the website AND a message will be communicated to the user, "Archiving an exercise will also remove it from the website, if you haven’t already done so."

**MOSCOW**
* Must have - Exercise is automatically unpublished from website when archived
* Must have - User is informed that exercise will be removed from the website

**User Testing Steps**
1. Archive an exercise
2. Observe message that it will be removed from the website
3. Check the website to ensure exercise has been removed

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
Disallow archiving until exercise is unpublished from website.
Here I'm actually un-publishing at the same time as archiving!

Closes #2159 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Goto the following url (it may prompt you to login first): https://jac-admin-develop--pr2215-feature-2159-disallo-5vj3g8aa.web.app/exercise/VG7qW7osx4eWUSIxFcT5/details/overview
- find an exercise that has been published and ensure the vacancy appears in the apply site
- archive the exercise and ensure a message appears saying 'This application is currently within the application window and is not published on the website' AND it no longer appears as a vacancy 
- unarchive the exercise and check that a message appears saying 'This exercise has been approved. Now you can publish it on the website' AND ensure it reappears as a vacancy.

See video attached below:

https://github.com/jac-uk/admin/assets/115651787/353c7b8c-80e3-45f6-8b36-251758b9d54c

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by HalcyonJAC — APPROVED** [review]

**Review by nickaddy — CHANGES_REQUESTED** [review]
This is not working for me; I tried on the Test Assessments Vue 3 exercise. It is published, but when I try to archive it, I just receive the 'Are you sure?' message shown below:

image

Additionally, the message when you try to archive a published exercise should read: "This exercise must be unpublished before it can be archived" and the user should be prevented from archiving until it has been unpublished and removed from Apply.

**Comment by nickaddy** [comment]
@warrensearle I've checked with Matt and he is content with how Omar has set this up. However, I've just run through the process and I think that when a user attempts to Archive a Live Published exercise, they should receive a modal: "This exercise is Live on Apply; by clicking accept, you authorise the exercise to be removed from Apply and archived" rather than the standard "Are you sure?" standard message. Is this possible?

**Comment by warrensearle** [comment]
@nickaddy of course, thank you. It will be done 👍

**Comment by warrensearle** [comment]
This has been updated now.

Exercise that is published:
image

Exercise that is not published:
image

**Comment by warrensearle** [comment]
Hey @nickaddy as agreed I've removed the bulk archive and bulk delete functionality and also disabled the Publish button for archived exercises.

Have also fixed a bug with the layout.

Please do review again

**Review by nickaddy — APPROVED** [review]
Happy days! Thanks for mopping up those other issues alongside :-)

**Pull request merged**
