### PR TITLE
#1725 Late applications

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
Allow admins to request a late application to a closed exercise.
Allow a senior leader to reject/approve a late application to a closed exercise.
Allow both admins and senior leaders to create, update, read and delete messages.
On approval a draft application is created.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

**Request A Late Application**
Login in as a user with permission to request late applications - e.g. jacstaff@judicialappointments.digital
Request a late application for a closed exercise (see video for demo)
_N.B. Late applications can only be requested for exercises which have been approved, open for applications and are now closed for applications_

**Approve A Late Application**
Login in as a user with permission to approve late applications - e.g. seniorleader@judicialappointments.digital
You should see a message on screen asking you to approve or reject a late application request (see video for demo)

**Action An Approved Late Application**
Login in as the user who requested a late application - e.g. jacstaff@judicialappointments.digital
You should see a message on screen informing you about the outcome of your request. Action it accordingly (see video for demo)

## Videos

Request A Late Application

https://user-images.githubusercontent.com/115651787/211017156-e048d187-6eed-4c8f-bbdb-99d6e961d80b.mov

Approve A Late Application

https://user-images.githubusercontent.com/115651787/211017307-1e8d4855-d3a4-4bd0-ab79-dd2a5d7d3da1.mov

Notify Approval Of A Late Application

https://user-images.githubusercontent.com/115651787/211017344-72f21689-e18f-4696-acc5-3923eec25e86.mov

Rejection Of Late Application And Reapply

https://user-images.githubusercontent.com/115651787/212375628-6d762071-cf03-4a4e-831c-28e2f2923034.mov

Note that if a user has multiple messages they are dealt with one at a time. Once one has been actioned (and closed) the next one appears until they are all done

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Related permissions
Have permissions been considered for this functionality?
- Permissions have been added / updated. Details:
- Added the following permissions:

- Can Create Message
- Can Update Message
- Can Delete Message
- Can Read Message
- Can Request Late Applications
- Can Approve Late Applications

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by andrew-isaac — CHANGES_REQUESTED** [review]
Doesn't work for me on my own account or the JAC Digital one. I don't have the add late application button, just the send reminders button. I tried the numerous accounts and had a scan of my user roles but don't see anything that jumps out at me. I finally got it to work the jacstaff account but there was no reminders button? One button is on one role but not the other role? I also tried to use the senior leader log in and got no pop up informing me of a late application to approve or reject

Senior Leaders account 

image

My Google account

image

JAC Staff Account

image

It is a bit confusing on whose account it will appear and how? I presume it is down to the user roles

**Comment by warrensearle** [comment]
Hey @andrew-isaac yes this was to do with getting the permissions right.

It is now working by logging in with our demo users as follows:

- jacstaff@ to request a late application
- seniorleader@ to approve or reject the late application request
- jacstaff@ to process the outcome of the late application request.

I have updated the 'how to test' instructions accordingly.

**Comment by warrensearle** [comment]
Recent updates to permissions and demo users mean this should be easier to test now. 🤞

**Review by HalcyonJAC — APPROVED** [review]
The functionalities work for me 👍

**Review by tomlovesgithub — APPROVED** [review]
👌good stuff works great

**Pull request merged**
