### PR TITLE
Feature/2150 testing hooks

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
Github and slack integration.

When a user clicks on the Report An Issue Link they will see a form to report an issue on the platform.
The first time a user does this they will be prompted to enter their Slack Member ID.

When a support ticket is raised in the Admin platform an issue is created in the github ticketing-system repository: https://github.com/jac-uk/ticketing-system/issues
The issue can also be viewed in zenhub: https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/board/home/board?repos=730628030
A message is sent to the Slack platform-issues channel detailing the issue.

When the github issue in the ticketing-system repo is either assigned to / unassigned from a user a Slack message is sent to the platform-issues channel mentioning the assigned/unassigned user with a link to the issue.

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

**Test 1**
- Login to Admin using [this preview url](https://jac-admin-develop--pr2279-feature-2150-testing-56l9hsxv.web.app)
- Navigate to a page of your choice (can be any exercise)
- Click on the **_Report an issue_** button (bottom left of screen)
- Try to submit the form without completing any fields: you should see errors at the top of the page specifying the fields you must fill in
- Follow the instructions in this video to determine your Slack Member ID - you will only need to do this the first time - and paste into the relevant field: 

https://github.com/jac-uk/admin/assets/115651787/574b29f3-4e23-42dc-b2de-2e68ed7de209

- Fill in the fields as instructed, capture a screenshot, then press the Submit button and wait for the form submission to complete 
- After a short wait you should see the form disappear and a popup will inform you that the issue was created

- A slack message will appear in the platform-issues channel looking like this:
Screenshot 2024-01-17 at 12 13 34

- Only users with github access can click on the link in the slack message above

**Test 2**
- Navigate to a page of your choice using the same link as above
- Click on the **_Report an issue_** button
- You should see the same form, but without the text field prompting you for your Slack Member ID

**Test 3**
- Repeat Test 1 but this time raise an issue for a candidate by clicking the appropriate radio button at the top of the form

For Digital Team only
If you have access to the ticketing-repository in github then perform the following steps: https://github.com/jac-uk/ticketing-system/issues
- Find your github issue with the Unique Issue Number you noted down from above (beginning 'BR_)
- Make sure the details in the issue are correct (according to the details you entered when you submitted the form on the website).
- assign the ticket to either DrieJAC or HalcyonJAC
- A slack message will appear in the platform-issues channel looking like this:
Screenshot 2024-01-17 at 10 25 05

- If you have access to the github repo you can press the github link in the Slack message above to ensure it goes to the issue
- Check that the person you assigned the issue to matches the name in the Slack message

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@drieJAC Feedback from internal testing, give me a shout if anything unclear:

- Turn off those Firestore backup alerts in the Slack channel (we should get to the bottom of the error on staging at some point)
- Delete all the test tickets currently on the board
- Add spinning timer on Submit button
- Do not include a reference in the Raise a support issue confirmation message - it's confusing having 2 reference number in ZH/GH - use the ZH/GH ticket #reference
- Include user notification (@user) in Slack alert generated when new issue created
- Include user notification (@user) in Slack alert generated when ticket assigned to/unassigned from a developer
- Amend format of new issue created alert in Slack channel:

The following critical issue was raised by **Addy, Nick**

Reference number: **#xxx** (this ref number has a hyperlink to the ticket number on ZH)
Description: not what i was expecting

Prior to UT: @nickaddy to finalise UT instructions

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@drieJAC Feedback from UT:

- two candidates experienced an issue with submitting the modal form (you are already investigating with Abdalla)
- need to add guidance on response times re priority selection (see below)
- complete ID mapping for Tom, Warren and Ko Wei (Ryan currently mapping to Ko Wei)
- we will test again next week to gain wider feedback, pls confirm all above ready for retesting

Response times:

Critical - a response will be provided within 2 hours
Major - a response will be provided within 24 hours
Minor - a response will be provided within 48 hours
Low - a response will be provided within 1 week

@Franceswog UT instructions need to be updated to include link to video (you'll need to copy it to a folder on Google drive) and clarity about which Slack channel we are using for testing. You'll need to add the users to the Slack channel as they join the session or maybe Norma could do that - make sure you know how to ;-)

**Review by HalcyonJAC — APPROVED** [review]

**Comment by drieJAC** [comment]
The two candidates experiencing an issue with submitting the modal turned out to be their user records were missing the uid field in the firestore database.
A nodescript will be run to fix this for UT today then a bugfix will be added to prevent it going forward.

**Comment by nickaddy** [comment]
@drieJAC Great news, Omar, this has passed UT. Let's discuss deployment to make sure we have everything in place before releasing, e.g. user guidance communicated on new process. 

@Franceswog To prepare user guidance document for sharing widely across user teams for COP 26/1
@nickaddy To prepare internal process guidance for input from team

**Pull request merged**
