### PR TITLE
Feat/2423 align admin with section 2d3d qualifications changes

### LINKED ISSUE #2423: Align Admin with Section 2d/3d qualifications changes on Apply
## Background
Following recent changes on Apply - the addition of a None of the above under `What are you qualified as?` and the making of follow-on questions optional in the case of that selection - it's necessary to make sure this is joined up on Admin. 

See https://github.com/jac-uk/apply/pull/1187

## Feature(s) Description

- [ ] Ensure admin view aligns with the above change
- [ ] Ensure any reports align with the above change

## User Testing Steps
No user testing required

## Ticket champion
Tom

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
closes #2423 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link: https://jac-admin-develop--pr2457-feat-2423-align-admi-o5n9agb4.web.app/exercise/X2tDg5AKt18xvzBRJFYW/applications/applied/application/g6e7d5gxp7FTEDnrwAPv
- Click Edit
- Change and save the answer for `Are you applying under Schedule 2(3)?`
    - If the answer is `Yes`, it should appear `None of above` option for Qualification
    - If the answer is `No`, it should not appear `None of above` option for Qualification
    - If the answer is changes, the Qualification(s) should be reset
Screenshot 2024-06-25 at 11 04 50

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@KoWeiJAC This is not working for me. First of all, there was no option set under eligibility in set-up (you have to choose 2d or 2(3). I've now set it to 2d and at that point the Are you applying under section 2d appeared. However, irrespective of my answer, None of the above appears in the dropdown. Also, it doesn't appear to reset when the initial answer to Are you applying under...  changes.

**Review by Franceswog — COMMENTED** [review]
I would have thought when you click 'No' the window below (Explain how etc) should not appear. It should only appear when you click 'Yes', which allows the candidate to explain how they gained their experience in law.. 

image

**Comment by KoWeiJAC** [comment]
> @KoWeiJAC This is not working for me. First of all, there was no option set under eligibility in set-up (you have to choose 2d or 2(3). I've now set it to 2d and at that point the Are you applying under section 2d appeared. However, irrespective of my answer, None of the above appears in the dropdown. Also, it doesn't appear to reset when the initial answer to Are you applying under... changes.



> @KoWeiJAC This is not working for me. First of all, there was no option set under eligibility in set-up (you have to choose 2d or 2(3). I've now set it to 2d and at that point the Are you applying under section 2d appeared. However, irrespective of my answer, None of the above appears in the dropdown. Also, it doesn't appear to reset when the initial answer to Are you applying under... changes.

@nickaddy 
Not sure if the exercise being reset, I set it to schedule 2(3) originally, thank you for fixing it.

I've had following changes:
- 'None of above' appears according to schedule question, it will change when schedule being selected not saving.
- Reset all the qualifications after the schedule question change saved. Because it will be to safer to reset the qualification after schedule being saved.
Could you help me to confirm if it is ok ? Thanks
https://github.com/jac-uk/admin/assets/156695133/1c600910-f141-4e1e-aeeb-264daa57fca3

**Review by nickaddy — APPROVED** [review]
@KoWeiJAC 👍

**Review by HalcyonJAC — APPROVED** [review]

**Review by NormaJAC — APPROVED** [review]
it works

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
