### PR TITLE
Upgrade Admin to use the latest Firebase library#1898

### LINKED ISSUE #1898: Upgrade Admin to use the latest Firebase library
**Background**
The Firebase update was planned in the Roadmap for Q4 2023, but it was postponed to early 2024 as lower priority work due to support for our current version still being available to later on in 2024. The plan is to upgrade Admin first, as we’ll get feedback/bug reports quicker from staff and if there are bugs then they’ll be lower impact than on Apply or QT platforms.

**Useful links**

https://firebase.google.com/docs/web/modular-upgrade

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
closes #1898 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?`
Go to the preview link: https://jac-admin-develop--pr2287-chore-1898-upgrade-a-0yppj7xs.web.app/
All of the functionality of the admin site, include but not limited to:
- Sign-in/Sign-out
- All tables
- All functionalities for creating/updating/deleting data
- All functionalities for upload/download/preview files

## Risk - how likely is this to impact other areas?
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Review by nickaddy — APPROVED** [review]
@KoWeiJAC I have not been able to locate any bugs; I have flagged to users to feed back to us if they experience any issues

**Review by Franceswog — APPROVED** [review]
No Issues here.

**Comment by KoWeiJAC** [comment]
@warrensearle 
> Hey @KoWeiJAC this is looking great. The only problem I have found so far is the following:
> 
> **Before** (fresh install of Admin running from `main` branch) All looks fine, no console errors image
> 
> **After** (fresh install of Admin running from this branch) Console error image
> 
> The back-end this is connecting to is unchanged however the error looks like a firestore permission error. Perhaps the new code is trying to access more from firestore than the previous code. Good luck!

Yeah, I saw these error before. It seems happen when page first loaded , but then it can fetch data from firestore successfully.
I think it's more like the issue of firebase v10 lib, I only change the functions to modular APIs and didn't modify any firebase settings. 
Maybe we can ignore this error and to see if new releases of firebase lib can fix it ?

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Review by NormaJAC — APPROVED** [review]
All ok

**Review by warrensearle — APPROVED** [review]

**Pull request merged**
