### PR TITLE
#2115 #2119 Bug fixes

### LINKED ISSUE #2115: BUG: Exercise. Website listing. Changing advert type should not change exercise state
Currently when Advert Type is changed on the Exercise Website listing page (see screen grab below) the exercise state is also being changed to 'ready'. Exercise state should not be effected by changing advert type.

image

### LINKED ISSUE #2119: BUG: Exercise. Task list. Application process does not show as DONE
On the Exercise Task List the Application Process task does not have a DONE tag shown even after editing and saving the Application Process form.

image

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?

Primarily this PR includes a number of bug fixes:
- BugFix: Changing advert type should not change exercise state #2115
- Bugfix: Panel pack search improvement
- Bugfix: Create an exercise from clipboard not working
- Bugfix: Applications list layout. Reduce margin
- Bugfix: Task list. Application process not showing as Done #2119
- Bugfix: Exercise overview broken when unlocked
- Bugfix: Stages search should include hint

This PR also enables the review/testing of basic functionality for Shortlisting and Selection tasks, however this will only be viewable for exercises configured to use 'Processing Version 2.0'. By default exercises use 'Processing Version 1.0'. Further work on shortlisting and selection tasks will happen in other tickets in the epic #1861.

Closes #2119
Closes #2115

## Who should test?
✅ Product owner
✅ Developers

## How to test?
Use the [preview url](https://jac-admin-develop--pr2166-feature-1868-wdp7jfg6.web.app/) and check that each of the above bugs have been fixed.

(Compare against admin-develop to see the bug before and after the fix)

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by Franceswog — COMMENTED** [review]
All the tasks has been completed with the label 'DONE' besides EMP tie breaker. I logged into the QT platform to complete the task , thereafter clicked on the green button to transfer application but it comes up with an 'Error' button. 

image

**Review by MattHowley — CHANGES_REQUESTED** [review]
FYI I was testing on develop using JAC00675

On the selection day tab, I noticed that the platform tallies the interview score, the situational questioning score and the overall score. I think SETs just convert the overall grades to a numerical score to determine merit order, not the interview and situational questions (or role play, strategic questioning etc). This, however, will need clarifying

Statutory consultation is not a 'pass' or 'fail'. It is simply the collation of information about candidates from the judiciary to be used as an additional piece of evidence by the selection day panel.

On the character and selection SCC, pretty sure I marked 3 candidates as passed but they were all marked as failed (could well have been my own mistake though!) By the time I'd noticed I'd already completed the section. I then went to stages and amended the candidate statuses there, first to 'passed sift' then to 'passed character and selection SCC'. On the stages tab though, the candidates moved to 'passed character and selection SCC' still remained in 'Shortlisted'. I later realised that you need to select 'passed shortlisting' in order to progress them to the next stage, which makes sense, but wasn't necessarily obvious as a user. Additionally, changing the candidates' status on the stages tab didn't amend them on the tasks tab as you might expect - they still all showed as failed. Think we need to consider cohesion between tasks and stages so if it updates in one place, it updates in the other. Perhaps even more ideal, all statuses would be dealt with through the tasks only, and we do away with the stages. Though I think we need a mechanism to unlock and change/remedy the tasks if need be.

EMP tie breaker - can we now transfer candidates to the QT platform? I know this feature wasn't available a few weeks ago so haven't tested

Because I didn't test the EMP tie breaker, I also couldn't test Independent Assessments or Character. However, given these occur before other tasks (logically, and as set out in the exercise timeline) why do they appear at the bottom of the list of tasks?

**Review by drieJAC — APPROVED** [review]

**Comment by warrensearle** [comment]
I have captured/moved the feedback above into epic #1861 for the following reasons:
 - this PR mainly contains bug fixes (plus enables testing of basic functionality for #1861)
 - further work on #1861 will happen in future tickets/PRs following a series of workshops with our users

**Review by Franceswog — COMMENTED** [review]
I am still unable to  successfully complete the EMP  tie breaker task. It still comes up with an error. 
image

**Comment by warrensearle** [comment]
> I am still unable to successfully complete the EMP tie breaker task. It still comes up with an error. 

Thanks @Franceswog I have moved this to a separate bug ticket as this problem exists on production too at the moment. So the fix to that and the fixes in this PR can be rolled out independently.

**Review by HalcyonJAC — APPROVED** [review]

**Review by Franceswog — COMMENTED** [review]
Selection day Task doesn't seem to work either. I clicked on continue on that task but it fails to show the 'Done' flag. Could this be the reason setting  up the EMP Tie-breaker doesn't work?  
image
I am also unable  to type into the 2 boxes , hence not allowing me move past this stage. 
image

**Review by nickaddy — APPROVED** [review]
As far as I can tell, these bugs are fixed :-)

**Comment by warrensearle** [comment]
> Selection day Task doesn't seem to work either. I clicked on continue on that task but it fails to show the 'Done' flag. Thanks @Franceswog this is a great spot, I have moved it to a future ticket as the functionality is hidden from general use

**Pull request merged**
