### PR TITLE
#2173 Independent Assessments

### LINKED ISSUE #2173: Independent Assessments
**Background**
**Independent Assessments request **
Could the wording in the message displayed just before an IA run is despatched, be changed from "candidate(s)" to "assessors"?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--571b6b7543741689168c68236b694479acd39f81/image.png)

**Independent Assessments request email signature**
If the "Email signature name" field in the Contacts tab could allow the use of a name rather than required an email address, as now IA requests are signed off using an email address, which looks a bit odd.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1JLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f603a81b5b9946a6a1c719d1ea7f42ba2d65bc8/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a59edec81ffab6398cd60fd3238e69c499b80cf/image.png)

**Independent Assessments reminder**
The phrasing also needs to be updated when sending reminders to assessors, as it’s got the "candidate" wording there too. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEpLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a019146229b2903fc2c92eee59943dec44c1898b/image.png)

**User Story** 
As an admin, I would like the word 'candidates' in the Independent Assessments request changed to 'assessors' so that I can see the correct title when sending IA requests.

**User Story** 
As an admin, I would like the "Email signature name" field in the Contacts tab changed to the Selection exercise manager's name, so that IA requests can be signed off using a name.

**User Story** 
As an admin, I would like the word 'candidates' in the Independent Assessments reminder changed to 'assessors' so that IA reminders show the correct title when sending IA reminders.

**Ticket Champion**
Richard Collumbell

**Happy Story**
Admins would be confident that they are sending out the right requests and reminders to Independent assessors, not the candidates.
Emails sent to assessors will have the Senior Selection Exercise manager's name at the bottom of the email sent to Independent Assessors.

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2173

Note: This PR needs changes on Digital Platform [#2173 Admin Independent Assessments](https://github.com/jac-uk/digital-platform/pull/981)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
1. Go to preview link: https://jac-admin-develop--pr2244-feature-2173-indepen-wskxjm6y.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/tasks/all/independent-assessments#notrequested

2. Go to "Not Requested" tab
- Select one assessment
- Click "Send Request" button
- It should appear a pop-up with related information (changed to X assessor(s)): 
image

3. Go to "Requested" tab
- Select one assessment
- Click "Send reminders" button
- It should appear a pop-up with related information (changed to X assessor(s)): 
image

4. Go to preview link: https://jac-admin-develop--pr2244-feature-2173-indepen-wskxjm6y.web.app/exercise/ONqUjAzhDS7rjh6dFJLB/details/contacts
- Click "Update exercise contacts"
- Change the "Exercise mailbox" to your email like "xxxxx@judicialappointments.digital"
- Enter the "Email signature name" like "Tester", then Save.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC There are no assessments showing up under Not requested:

image

**Comment by nickaddy** [comment]
@HalcyonJAC So the Notify email template uses the email signature name rather than the exercise mailbox content as sign-off now?

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC There are no assessments showing up under Not requested:
> 
> image

@nickaddy I have reset some assessments. You should be able to see some assessments under "Not requested".

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC So the Notify email template uses the email signature name rather than the exercise mailbox content as sign-off now?

@nickaddy Yes, the IA request email template uses the email signature name as sign-off.

**Review by Franceswog — APPROVED** [review]
All works as expected- No issues

**Review by nickaddy — APPROVED** [review]

**Review by NormaJAC — COMMENTED** [review]
Works as expected.

**Review by drieJAC — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]

**Pull request merged**
