### PR TITLE
Feature/2231 Improve Eligibility Report functionality

### LINKED ISSUE #2231: Improve Eligibility Report functionality
**Background**
At the digital meeting on 28/11/2023, eligibility issues improvements were discussed and a number of bugs on the current platform. The objective of this ticket is to provide comprehensive candidate data on the `Eligibility issues` report page, allowing the SET to make recommendations and then download a document in the format required for the annex to the SCC report (covered in [ticket #2300](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2300))

**Feature(s) Description** 

- Currently the relevant candidate data is not feeding through to the report page; this should be addressed by presenting the information as shown below with `Met `/ `Not met` returned for each criterion (not met would require further manual consideration by the SET)

> For Legal Exercises: 

> - **Professional Qualification:** `Met `= the candidate meets the qualification criteria specified in the exercise set-up
> - **PQE:** `Met `= the candidate meets the qualification criteria specified in the exercise set-up (generally 5 or 7 years) 
> - The platform needs to take into account the following when calculating the PQE:
> - It's easiest to work back from current role; if that is equal to the PQE requirement, no need to go back any further assuming it is a full-time role
> - The PQE role must include at least one of law-related tasks a-h to be included in the calculation
> - If PQE role includes only law-related task i, it should not be included in calculations and if the PQE requirement is not met elsewhere, this should flag the PQE as `Not Met`
> - The total amount of PQE should be calculated and displayed after `Met `/ `Not Met` in the format years and months (as a fraction), e.g. 3 years 4.5 months
> - **Previous Judicial Experience:** `Met `= the number of sitting days acquired by the candidate (PQE where option a (the carrying-out of judicial functions of any court or tribunal) is greater than or equal to what is requested AND the experience is Judicial not Quasi-judicial (Quasi-judicial would trigger a `Not Met` return)
> - **Reasonable length of service:** Met = the difference between the candidate age on the date of SCC meeting and 75 is greater than or equal to the RLoS specified in the exercise set-up
> - If candidate has answered No to the RLoS question, the content of the box below should be included:

> For Non-legal Exercises: 

> - **Professional Registration:** displays any memberships, e.g. GMC, RICS
> - **Reasonable length of service:**  Met = the difference between the candidate age on the date of SCC meeting and 75 is greater than or equal to the RLoS specified in the exercise set-up

- Fix Recommendation dropdown so that selection is retained on release 
- Remove 'Reject Non-declaration' from the options - this does not apply to Eligibility
- Add checkbox at the top with the text 'Display only candidates with Eligibility issues' - this toggles between all candidates being displayed and just the ones that don't meet some or all of the criteria
- Add a `Download SCC Annex report` link at top of page

**Ticket Champion**
Nick

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2231.

- Fix the "Recommendation" dropdown and "Reason for recommendation" textbox.
- Remove "Reject Non-declaration" from the issue status options.
- Add a checkbox at the top with the text "Display only candidates with Eligibility issues". This checkbox toggles between all candidates being displayed and just the ones that don't meet some or all of the criteria.
- Add a "Download SCC Annex report link" at the top of the page. The functionality will be implemented in #2300.
- Show the information as shown below with Met / Not met returned for each criterion (not met would require further manual consideration by the SET).
  
  image

Note: This PR requires changes in [digital-platform: Feature/admin 2231 Eligibility Report](https://github.com/jac-uk/digital-platform/pull/1024).

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

Example exercises:
- Legal exercise: 
  https://jac-admin-develop--pr2332-feature-2231-improve-hpvso0a0.web.app/exercise/pmhY2nNEQFg4OXzSDPYw/reports/eligibility-issues
- Non-legal exercise:
  https://jac-admin-develop--pr2332-feature-2231-improve-hpvso0a0.web.app/exercise/mof6mdC6grPuF8xQYwUA/reports/eligibility-issues

1. Check if the "Recommendation" dropdown and "Reason for recommendation" textbox work properly.
2. Check if "Reject Non-declaration" has been removed from the issue status options.
3. Check if the checkbox "Display only candidates with Eligibility issues" works properly.
4. Check if each application's information with Met/Not Met shows correctly.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by Franceswog — APPROVED** [review]
Instruction from 1-4 and other functionalities for both Legal and Non legal -  no issues to report.

**Comment by nickaddy** [comment]
@HalcyonJAC This is looking really good, Ryan. I've been playing around with data in a couple of the apps. Under Shakin' Stevens, the PJE (sitting days) appears to work, but with Jennifer Saunders I have played around with the two entries; they now total 60 sitting days, but PJE is flagged as met even though 300 days are required.

I'm also wondering about on Non-legal exercises, if no professional registrations are requested, would those candidates disappear when the 'Display only..' tickbox was ticked?

**Comment by nickaddy** [comment]
@HalcyonJAC Another thought - suggest we need a disclaimer on the PQE calculations; candidate inputs only month and year, but we are calculating years, months, days. Obviously there are potential inaccuracies there, even if we fed back years and months only. For example, I'm assuming if a candidate entered, e.g. March 2001 - April 2001, the platform would calculate this as 31 + 30 = 61 days. Thoughts? What's the maximum range of error? Should we consider some kind of flag for candidates that are very close to the required PQE?

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC This is looking really good, Ryan. I've been playing around with data in a couple of the apps. Under Shakin' Stevens, the PJE (sitting days) appears to work, but with Jennifer Saunders I have played around with the two entries; they now total 60 sitting days, but PJE is flagged as met even though 300 days are required.
> 
> I'm also wondering about on Non-legal exercises, if no professional registrations are requested, would those candidates disappear when the 'Display only..' tickbox was ticked?

1. I have redeployed the cloud function. Could you test it again, please?
2. For now the checkbox "Display only candidates with Eligibility issues" will not take "Professional Registration" into account. Hope it makes sense.

**Comment by nickaddy** [comment]
@HalcyonJAC On the first point, I think it's quite a good illustration of my second point above about how the PQE is calculated, in this case it is Jan 2007-Dec 2008 and Jan 2009-Dec 2009. That is being presented as 2y10m. I'm not saying that's wrong, but it could also be displayed as 3y, do you see what I mean? Can you clarify how the calculation is done pls?

On point 2, it seems obvious, but can you confirm that it only applies to non-legal exercises?

**Review by NormaJAC — APPROVED** [review]
I tested all 4 points for the legal and non-legal exercises, all worked as expeected.

**Comment by HalcyonJAC** [comment]
@nickaddy Here is an example of how the range will be calculated:
- `Jan 2007-Dec 2008`: the range is calculated from `2007-01-01 00:00:00` to `2008-12-01 00:00:00` which is 1 year and 11 months. 
- `Jan 2009-Dec 2009`: the range is calculated from `2009-01-01 00:00:00` to `2009-12-01 00:00:00` which is 11 months.
So the total length is 2 years and 10 months.

On point 2, the filter only applies to non-legal exercises.

**Comment by nickaddy** [comment]
@HalcyonJAC On this basis, it seems that the maximum 'extra days' the platform could calculate would be 1 month, e.g. candidate states January as a start date but actually started on 31 January; we don't need to worry about 'under-calculation' on the end date. As a solution, could we subtract 1 month from the total calculated before feeding it into the Met/Not met calculation? Or just have the platform flag as Not Met if it is within 1 month of the PQE requirement? In reality, this will happen in a minority of cases, but we should cover all bases to give SETs confidence in the feature.

**Comment by HalcyonJAC** [comment]
@nickaddy Yes, I could subtract 1 month from the total calculated before feeding it into the Met/Not met calculation.

**Review by nickaddy — APPROVED** [review]
@HalcyonJAC This does the job! 🥇

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
