### PR TITLE
Feat/2387 improve eligibility report v2

### LINKED ISSUE #2387: Improve Eligibility report v2
## Background
Following November's Digital meeting, improvements to the Eligibility report, including Met/Not met flags, and several bug fixes were implemented. There has been further discussion with Rob, Dan and Matt highlighting the challenges of automating the creation of SCC Eligibility annexes due to requested format of information and the lack of consistency in eligibility requirements across multiple exercises. The objective with this ticket is to focus on the annexes required for Legal Exercises - in particular, statutory eligibility reqs (qualifications and PQE) and non-statutory reqs (PJE and RLoS.)

## User Story
As an Admin, I would like to be able to input the eligibility recommendations content on the platform so that I can download the specified SCC-ready annexes for the SCC report.

## Benefit(s) to user (if not already clear from User story)
Admins will be able to add recommendations for individual annexes rather than just an overall recommendation; this will support generation of the annexes according to the set template.

## Feature(s) Description

- [ ] Reconfigure eligibility report screen for legal exercises as in [Miro board](https://miro.com/app/board/uXjVKZ-qbUY=/?moveToWidget=3458764587848654751&cot=14) (covers additional points below too)
- [ ] Add additional content from two fields on new application form
- [ ] Add additional recommendation dropdowns
- [ ] Add additional free text fields
- [ ] If there is no eligibility criteria specified, e.g. for PJE, that section should not be included onscreen

## Acceptance Criteria 
It's done when:
-  Admins can make separate recommendations for Stat criteria, PJE and RLoS on Legal exercises
-  Admins can view candidate responses where they haven't met PJE or RLoS on Legal exercises
-  Admins can add separate comments about their separate recommendations for Stat criteria, PJE and RLoS on Legal exercises

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
We are aiming to be able to create the content for Legal Statutory, PJE and RLoS SCC eligibility annexes on the platform. Test the showcased functionality by interacting with the page as you would when trying to conduct this activity.

## Feature Champion
Arti Sherry

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
closed #2387 

- Admins can make separate recommendations for Stat criteria, PJE and RLoS on Legal exercises
- Admins can view candidate responses where they haven't met PJE or RLoS on Legal exercises
- Admins can add separate comments about their separate recommendations for Stat criteria, PJE and RLoS on Legal exercises

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- New Legal exercise: Can add recommendation and reasons for individual eligibility issue
    - Go to the preview link: https://jac-admin-develop--pr2390-feat-2387-improve-el-s0bfjq10.web.app/exercise/S9V9R15MGRjCDHdcRQRZ/reports/eligibility-issues
    - Click `Refresh` button to prepare eligibility issue data.
    - It should appear recommendation dropdown lists for each eligibility issue.
    - If the recommendation being selected, it should appears `Reasons not satisfied` box.
    - It should display candidate comments for `Previous Judicial Experience`  and `Reasonable length of service` issue
    - `Recommendation` and `Reasons not satisfied` changes can be saved.
- Existing Legal exercise: The original overall recommendation will become the recommendation of individual eligibility issue
    - Go to the preview link:  https://jac-admin-develop--pr2390-feat-2387-improve-el-s0bfjq10.web.app/exercise/pmhY2nNEQFg4OXzSDPYw/reports/eligibility-issues 
    - It should appear recommendation dropdown lists for each eligibility issue.
- Non Legal exercise: Stay the same as before, can add  an overall recommendation for eligibility issues
    - Go to the preview link:  https://jac-admin-develop--pr2390-feat-2387-improve-el-s0bfjq10.web.app/exercise/OTzmqJ0KOdyT4h1azw7X/reports/eligibility-issues
    - Click `Refresh` button to prepare eligibility issue data.
    - It should appear one overall recommendation dropdown lists for eligibility issues.
    
## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by Franceswog — APPROVED** [review]

**Review by Franceswog — APPROVED** [review]

**Review by NormaJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@KoWeiJAC I'm afraid you've misread this ticket: pls look again - for Statutory eligibility, we are asking to make a single recommendation for Statutory criteria, i.e. we need to display the flags for Prof Qualification and PQE but have only one recommendation dropdown and one reason free text field for the Statutory section.

Non-statutory section looks correct.

One other comment: is it possible to have a heavier line between candidates than we have within each candidate section?



I think this will help to pick out separate candidate entries.

**Comment by KoWeiJAC** [comment]
> * https://jac-admin-develop--pr2390-feat-2387-improve-el-s0bfjq10.web.app/exercise/S9V9R15MGRjCDHdcRQRZ/reports/eligibility-issues

@nickaddy 
Thank you for finding this incorrect place out.
I've had adjustments accordingly. The statutory issues share one overall recommendation and reason.
Also, I've made the line below candidate name heavier.
Could you help me to review those places again ?
Thanks!

**Comment by nickaddy** [comment]
@KoWeiJAC The changes look good - thank you for remedying. However, there is a strange error occurring: when you make changes to the RLoS section dropdown and/or free text fields, the same changes are made to the equivalent fields in statutory section; pls investigate. I am happy to demo if it's not happening for you.

**Comment by KoWeiJAC** [comment]
> @KoWeiJAC The changes look good - thank you for remedying. However, there is a strange error occurring: when you make changes to the RLoS section dropdown and/or free text fields, the same changes are made to the equivalent fields in statutory section; pls investigate. I am happy to demo if it's not happening for you.

@nickaddy 
Thank you for finding this bug, I've had a fix for it, could you help me to test it again?
Thanks

**Review by warrensearle — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@KoWeiJAC In reviewing the report download, I've noticed a couple of issues on this ticket:

- When content of candidate’s application is updated, e.g. RLoS and PJE sections, then the eligibility report refreshed, the updates are not see on the eligibility report page
- When you click `View application` (to the right of candidates' names,) the page should open in a new tab
- Under Non-statutory section, `Reasons not satisfied` title of both free text fields should read `JAC Comments`

**Comment by nickaddy** [comment]
@KoWeiJAC Some more comments from last week's UT:

- The test exercise had no PQE eligibility set so how was it awarding Met flags to candidates? I’ve changed it to 5y and refreshed but the calculation of PQE does not seem to be working properly
- Related to the first point: Duration content in brackets missing after first candidate is missing
- 
- We need to rethink this filter; it was designed for just one recommendation dropdown: could it include candidates where 1 or more of the recommendation dropdowns is unassigned?
- 
- Once you have sorted the above, could you pls create an application that does meet all the criteria so that we can test the `Display only candidates with Eligibility issues` tickbox?

**Comment by KoWeiJAC** [comment]
> @KoWeiJAC Some more comments from last week's UT:
> 
> * The test exercise had no PQE eligibility set so how was it awarding Met flags to candidates? I’ve changed it to 5y and refreshed but the calculation of PQE does not seem to be working properly
> * Related to the first point: Duration content in brackets missing after first candidate is missing
> * 
> * We need to rethink this filter; it was designed for just one recommendation dropdown: could it include candidates where 1 or more of the recommendation dropdowns is unassigned?
> * 
> * Once you have sorted the above, could you pls create an application that does meet all the criteria so that we can test the `Display only candidates with Eligibility issues` tickbox?

@nickaddy 
The refresh button is a little bit tricky, to prevent the system reset the recommendations, it only set one application for one time. It means if the application is added to report, this application won't be refreshed for not overwriting the existing recommendations. But the refresh button can add newly added applications to report. This mechanism is the same as the character issue report.

To improve it, maybe we can refresh(update) the application which have no recommendations. If the application have any recommendation being set, the refresh would skip this application for not overwriting those recommendations.
Would you think it's workable ?

**Comment by KoWeiJAC** [comment]
> * The test exercise had no PQE eligibility set so how was it awarding Met flags to candidates?

@nickaddy  The test exercise had no PQE eligibility set so how was it awarding Met flags to candidates? => The system will make the PQE to be Met as default if the PQE years is not set.
Do we need to have change on this behaviour?

**Comment by nickaddy** [comment]
It looks like the only candidates that were flagged as Not Met were the ones that entered no work experience at all. If you check Exercise setup, the options under Eligibility Information are 5y, 7y or other - where you enter the number of years required. I don't understand how this exercise was created with 0 years PQE. If that is correct, even the candidates with no work experience should be flagged as Met.

**Comment by KoWeiJAC** [comment]
> It looks like the only candidates that were flagged as Not Met were the ones that entered no work experience at all. If you check Exercise setup, the options under Eligibility Information are 5y, 7y or other - where you enter the number of years required. I don't understand how this exercise was created with 0 years PQE. If that is correct, even the candidates with no work experience should be flagged as Met.

Just had a test, when creating the legal exercise, the PQE field is not required, so user can leave it empty and the PQE will be 0 as default.
I was using this exercise for test: https://jac-admin-develop--pr2390-feat-2387-improve-el-s0bfjq10.web.app/exercise/l6idrKzbXLr7BdJxmZvk/details/eligibility

Not sure of all the legal exercise need to look on PQE? If so, maybe we can make the PQE field required when creating exercise. To ensure PQE is greater than 0 and the candidates with no experience will be fagged Not Met. 

Screenshot 2024-05-20 at 16 34 09

**Comment by nickaddy** [comment]
@KoWeiJAC I agree with your proposal above - the PQE field for legal exercises must be mandatory and any candidates that do not enter any experience flagged as Not Met (in addition to those that do not meet the required PQE.) 

For reference, non-legal exercises do not request PQE according to my understanding.

**Review by drieJAC — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
> @KoWeiJAC I agree with your proposal above - the PQE field for legal exercises must be mandatory and any candidates that do not enter any experience flagged as Not Met (in addition to those that do not meet the required PQE.)
> 
> For reference, non-legal exercises do not request PQE according to my understanding.

@nickaddy I have mandated PQE field for legal exercises.

**Comment by nickaddy** [comment]
@HalcyonJAC I can't find my comment, maybe it was in Slack, regarding the filter for unassigned, has this been fixed? The dropdown options should be All issues and Unassigned - the latter would show candidates where any of the 3 recommendations are not selected or any of the 3 free text fields not populated. Could you address the above pls?

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC I can't find my comment, maybe it was in Slack, regarding the filter for unassigned, has this been fixed? The dropdown options should be All issues and Unassigned - the latter would show candidates where any of the 3 recommendations are not selected or any of the 3 free text fields not populated. Could you address the above pls?

@nickaddy I have fixed the filter. Could you retest it, please?

**Comment by nickaddy** [comment]
@HalcyonJAC Looking good, Ryan. Can you pls:

1. Remove the `Generate report` button
2. Confirm how you have approached the Refresh button issue, i.e. what happens if content has already been input to the Eligibility report?

**Comment by HalcyonJAC** [comment]
@nickaddy 
1. The "Generate report" button has been removed.
2. When users hit the Refresh button, it will populate data from applications again but also keep the fields (Recommendation, Reasons not satisfied, JAC comments).

**Pull request merged**
