### PR TITLE
1307 activity logging

### PR DESCRIPTION
**Pull request by HalcyonJAC**
**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [x] Be proactive in getting your work approved 💪

---
## What's included?
- Log an event when an exercise is published or unpublished

## Who should test?
✅ Product owner
✅ Developers

## How to test?
- Log into the admin portal and make changes to an exercise to trigger an event being logged
- Go to the Events page (via the menu item in the top right of the page) and check that an event has been logged.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by lloback — APPROVED** [review]

**Comment by lloback** [comment]
@HalcyonJAC we need instructions here, please. What to check? What to look for? What visible change is doing?

**Comment by JeremykJAC** [comment]
@lloback This issue is still in progress. Should be in review soon.

**Comment by warrensearle** [comment]
@HalcyonJAC @JeremykJAC any update on this one?

**Comment by HalcyonJAC** [comment]
Hi. I have merged what changes I can from the main branch into this one but need help with the conflicts in `src/views/Exercise/Applications/Application.vue` due to the sheer number of them. I am not sure what code changes should stay and what code is now redundant.

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
