### PR TITLE
Feature/2552 Updates to character task/report in line with changes

### LINKED ISSUE #2552: Updates to Character task/report in line with changes
## Background
Following updates to the application form character section described [here](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/apply/1209) and to Application view on Admin described [here ](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2551), are there any impacts elsewhere that should be considered? If none, this ticket can be deleted.

## Feature(s) Description
Clearly describe the new functionality/change(s) to existing functionality.
Include a link to a Miro board/image if appropriate.

- [ ] Feature

## Acceptance Criteria 
Specify the requirements of the primary user(s) for the change, update, or new feature - use the format: 
It's done when...

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2552 

- Update the "Agency report" on the application view.

Related PR: [digital-platform: Feature/admin 2552 Update character task/report in line with changes #1215](https://github.com/jac-uk/digital-platform/pull/1215)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

[Example application](https://jac-admin-develop--pr2576-feature-2552-updates-mutr5irw.web.app/exercise/Biyjd07Xz2usL9yXjtjV/applications/applied/application/DmtSTqTUDD2d0aihvOQ2#agency)

1. Go to the Agency report tab of an application.
2. Check if the data under the HMRC section displays correctly.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/user-attachments/assets/f92894b3-fcef-4f22-a342-0e18878ee88f

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC I'm seeing the old version of the statements here; they should reflect the new character questions, i.e.

- Has entered into an Individual Voluntary Agreement (IVA) or other similar arrangement
- Has filed late tax returns and/or made late tax payments
- Has filed late VAT returns and/or made late VAT payments
- Has ever been fined by HMRC :+1:
- Is aware of any open HMRC enquiries into their tax affairs :new:

**Comment by HalcyonJAC** [comment]
@nickaddy Thank you for spotting that. I have updated the new character questions. Could you test it again, please?

**Comment by nickaddy** [comment]
@HalcyonJAC The questions now look good, but I noticed two other things:

- I have populated some of the fields in [this application](https://jac-admin-develop--pr2576-feature-2552-updates-mutr5irw.web.app/exercise/Biyjd07Xz2usL9yXjtjV/applications/applied/application/DmtSTqTUDD2d0aihvOQ2#agency) but there is an error with the content being returned
image
- The Character questions [here ](image)are not updated, is that because Ko Wei's work is in a separate PR?

**Comment by HalcyonJAC** [comment]
@nickaddy 
1. What's the error? 
2. Yes, it's in a separate PR.

**Comment by nickaddy** [comment]
@HalcyonJAC Check the screen shot above: the code appears to be being pulled through rather than the content

**Review by Franceswog — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
@nickaddy I have fixed the display of the character content. Could you check it, please?

**Review by nickaddy — APPROVED** [review]
@HalcyonJAC @KoWeiJAC 👍

**Review by NormaJAC — APPROVED** [review]
All ok

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
