### PR TITLE
Bugfix/Issue-190 Self assessment extraction

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?

Mentions [issue 190](https://github.com/jac-uk/ticketing-system/issues/190)

- Enable to set up the question and word limit of the assessment.
  Question list:
  - Exercising Judgement
  - Possessing and Building Knowledge
  - Assimilating and Clarifying Information
  - Working and Communicating with Others
  - Managing Work Efficiently
  - Leadership
  - Legal and judicial skills
  - Personal qualities
  - Working Effectively
- Display the questions and the answers in the application view.
- Show line breaks on the extracted self-assessment content.

## Who should test?
✅ Product owner
✅ Developers

## How to test?

**Set up questions and word limits for "Self Assessment with competencies"**
1. Go to "Assessment options" and tick "Self Assessment with competencies".
2. Add questions and word limits aligned with the Word document.

**Apply for the application**
Follow the test instructions in [Bugfix/Issue 190 Self assessment extraction #1138](https://github.com/jac-uk/apply/pull/1138) to apply for an application.

**Application view**
Example application: https://jac-admin-develop--pr2315-bugfix-issue-190-sel-rbj0ixya.web.app/exercise/nrNvxQxa38XkFrE0ps5j/applications/draft/application/XpynYgjoDCHg46wGO1Bn

1. Go to "Self assessment competencies" of an application.
2. Check if the self assessment content shows correctly with link breaks.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

Set up questions and word limits for "Self Assessment with competencies"

https://github.com/jac-uk/admin/assets/79906532/23456286-acb8-41d3-9e15-bf2ae261adcc

Application view

image

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Review by Franceswog — APPROVED** [review]
Self assessment doc works as expected with line breaks..

**Comment by nickaddy** [comment]
@HalcyonJAC I'm getting an error when I try to upload the SA document? Save and continue changes to Error

**Comment by HalcyonJAC** [comment]
@nickaddy could I double-check the preview URL you used on apply? Is this one https://jac-apply-develop--pr1138-bugfix-issue-190-sel-a9ov50fs.web.app?

**Review by nickaddy — APPROVED** [review]
@HalcyonJAC I am absolutely delighted to say that this works for me!!!!!!!!!!

**Pull request merged**
