### PR TITLE
Feature/2352 Character Report functionality v2

### LINKED ISSUE #2352: Character Report functionality v2
## Background
Character reporting has been recently iterated in February and March, however, in conversations with SETs and Secretariat, it is clear that we need to go further to provide a workable solution that fully delivers on the promise of an SCC-ready Annex B1.  

**There is a little info outstanding below, but it would be helpful if you could produce an approximate estimate as we will be working on this item in the next sprint.**

## User Story
As an Admin user, I would like to be able to input all the data necessary on the platform so that it can be presented to the Secretariat for review prior to export directly for the SCC report.

## Feature(s) Description

- [x] Make the character information displayed to the users (application record on Admin) editable and formattable. The candidate's original application data should be retained on the application record.
- [x] The character information presented to the user on screen should be played back in the following format (Motoring example given, but same applies to all offence types - see full Miro [here](https://miro.com/app/board/uXjVKb0Ep0o=/?moveToWidget=3458764584228542233&cot=14))

- [x] The character information should be played back on screen in the following order: Motoring Offences, Fixed Penalty Notices & Penalty charge notices, Criminal Offences, Financial issues, Professional Conduct, Other matters.
- [x] Add an edit button that allows the onscreen content to be edited and reformatted and a Done button that allows the edited content to be saved.

- [x] Add the following options to the `Offence Category` dropdown: `Single Fixed Penalty Notices & Penalty Charge Notices`, 'Multiple Fixed Penalty Notices & Penalty Charge Notices'

- [x] Rename the following options to the `Offence Category` dropdown:
- Single financial offence > Single financial issue
- Multiple financial offences > Multiple financial issues
- Single professional conduct > Single professional conduct matter
- Multiple professional conduct > Multiple professional conduct matters

- [x] Reorder the items in the `Offence Category` dropdown as shown in the image below

- [x] Create a new `Guidance reference` tickbox (multiple selection permitted) section **after** `Offence category` and populate with these options:
- Criminal offences: paras 21-24
- Motoring offences: paras 25-30
- Fixed penalty notices: paras 31-34
- Financial insolvency and debt: paras 35-38
- Financial VAT and Tax: paras 39-43
- Professional conduct: paras 44-57
- Further disclosures: paras 58-65

- [x] Create a new field `SCC decision` dropdown containing options Proceed, Reject, Defer - this follows the `Recommended SCC Approach` field

## Acceptance Criteria (optional/delete if not used)
It's done when users can download an SCC-ready Annex B1 from the platform.

## User Testing Steps
TBC

## Feature Champion
Nick

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2352 

Related PR: [digital-platform: Feature/Admin 2352 Character Report v2](https://github.com/jac-uk/digital-platform/pull/1080)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Example exercise: https://jac-admin-develop--pr2372-feature-2352-charact-fqkz72tn.web.app/exercise/FpV4enhw0yWFb9htWO7y/reports/character-issues

1. Check if the character information is editable and formattable.
2. Check if `Single Fixed Penalty Notices & Penalty Charge Notices` and `Multiple Fixed Penalty Notices & Penalty Charge Notices` are added to the `Offence Category` dropdown.
3. Check if the options show correctly in the `Offence Category` dropdown:
    - Single financial offence > Single financial issue
    - Multiple financial offences > Multiple financial issues
    - Single professional conduct > Single professional conduct matter
    - Multiple professional conduct > Multiple professional conduct matters
4. Check if the new `Guidance reference` tickbox shows correctly.
5. Check if the new `SCC decision` dropdown shows correctly.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

Demo:

https://github.com/jac-uk/admin/assets/79906532/5bf487dc-c020-44e4-9489-7a68403def8c

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by Franceswog — APPROVED** [review]
All sections work with the right data in place, No issues to report.

**Review by nickaddy — CHANGES_REQUESTED** [review]
@HalcyonJAC Good stuff, Ryan. I have a few requests:

- When I refresh the page, any edits I made to the content presented are lost; where is the edited data stored?
- Rename `SCC approach` > `SCC Decision`
- Investigations field is missing from professional conduct (misconduct/negligence) section entries (showing as no information)

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC Good stuff, Ryan. I have a few requests:
> 
> * [ ]  When I refresh the page, any edits I made to the content presented are lost; where is the edited data stored?
> * [x]  Rename `SCC approach` > `SCC Decision`
> * [ ]  Investigations field is missing from professional conduct (misconduct/negligence) section entries (showing as no information)

@nickaddy 
1. When you hit the refresh button, it will populate/format the raw data of the character issues into a new field. There is a flag that indicates whether the character issues have been populated/formatted or not. So if you hit the refresh button again, it will check the flag first to ensure the data will not be overridden.
2. Sorted.
3. "No information" has been sorted. There are only two fields from the professional conduction section entries.
    Character-section-from-App-form

**Comment by nickaddy** [comment]
Thanks, @HalcyonJAC, I can see that the edited is content is now saving 👍

My third point above is this: in the candidate's application you have fields marked which do not appear to be replicated in the character report:

image

So you can't see here, whether the claim falls under negligence or misconduct:
image
It might be that this is not necessary if the information provided under details is insufficient, but I'm not sure where those fields come from.

**Review by nickaddy — APPROVED** [review]
👍

**Comment by nickaddy** [comment]
Can you confirm the name of the new field created to store the editable candidate character information and where this is stored in FB pls?

**Pull request merged**
