### PR TITLE
#933 Capture cut off score

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?

The ability to capture a cut-off score from within the QT Score Report and set the status of applicationRecords that are lower / higher than X.

The ability to change individual (or multiple) application statuses by selecting the application and clicking Set status

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

### Cut off scores
- Go to QT Report and click 'Set pass mark'
- Enter the cut off score and set the statuses
- Check the statuses of the applicationRecords (note: I can't find the application status anywhere in the UI which may need to be fixed as part of a different task)

### Update status
- Click on an individual score from the QT report
- Select one or more applications
- Click 'Set status'
- Select a status and continue
- Check the status(es) of the applicationRecords relating to the application you updated. (note: I can't find the application status anywhere in the UI which may need to be fixed as part of a different task)

https://user-images.githubusercontent.com/79906532/124025875-e60a3200-d9e8-11eb-8a80-31b47ee1bda9.mp4

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
Looks beautiful to me 👍 
✅ Code reviewed

**Comment by HalcyonJAC** [comment]
Preview url now works after deploying functions to develop :)

**Comment by warrensearle** [comment]
✅ Tested via preview URL

**Review by tomlovesgithub — APPROVED** [review]

**Review by mbrookeswebdev — APPROVED** [review]

**Comment by KateMJAC** [comment]
Sent to UTG on 07/07/21. Update to follow.

**Review by KateMJAC — COMMENTED** [review]
Sent to UTG on 07/07/21. Update to follow.

**Comment by joy-ade** [comment]
@warrensearle Feedbacks from UTG the set pass mark button is greyed out. Testers are unable to set mark

**Review by joy-ade — APPROVED** [review]
Approved by product team and UTG

**Comment by HalcyonJAC** [comment]
@joy-ade The merge conflicts are now resolved :)

**Pull request merged**
