### PR TITLE
#945 Improve analysis of qualifying test questions

### PR DESCRIPTION
**Pull request by lloback**
## What's included?
- Changed the TAB title from "Logs" to "Connection Logs"
- Created the "HISTORY" tab
- Added Analytics information and the amount of time user spent on the question

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
You need to start or edit a test on the apply
- Situational Judgement
- Critical Analysis
- Scenario

On each of the tests you will be able to see a new TAB called HISTORY
image
This tan will contain analytics information about the test

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
This task should be performed in conjunction with the apply#517

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by mbrookeswebdev — CHANGES_REQUESTED** [review]
Perhaps numbers of questions in History tab should start from 1, rather than 0. 

And 23:59:40 start line in this case is a little confusing. Maybe it's worth to remove it or set to 00:00:00 if the intention is to show how long it took the candidate to look at the question.


QThistory

**Comment by lloback** [comment]
@mbrookeswebdev I've did the changes that you asked on the PR:
1.  Changed the indexed question number, to be "Question 1" instead of "Question 0"
2. Removed the "23:59:40" meaning that the first item is always "00:00:00"

**Review by mbrookeswebdev — APPROVED** [review]

**Review by warrensearle — APPROVED** [review]
Looks good to me 👍

**Review by HalcyonJAC — APPROVED** [review]
This looks fine, but I would make it more legible by making the Question marker bold or something - as its a lot of text in the same style which can make it difficult as so:

image

**Review by KateMJAC — COMMENTED** [review]
This has been sent to UTG. An update will follow. 

It looks really exciting!!!!

**Review by KateMJAC — COMMENTED** [review]
Hello @lloback, I just tested this and the history logs didn't populate. I checked during the QT before I submitted the application and after I submitted and the QT was closed and scored, but I was unable to see any logged behaviour in the history tab.

**Comment by lloback** [comment]
> Hello @lloback, I just tested this and the history logs didn't populate. I checked during the QT before I submitted the application and after I submitted and the QT was closed and scored, but I was unable to see any logged behaviour in the history tab.

Did you use the link? https://jac-admin-develop--pr1317-feature-945-qt-analy-0sef2z9x.web.app/

**Comment by lloback** [comment]
TO test this you need to use the link from the other PR on apply.

**Comment by KateMJAC** [comment]
Hello @lloback yes, i'm sure I used the link on #774 PR. I can try it again, as it's possible I mixed the two up. 

This is out with the UTG so we'll see how they go. They have been provided the two different URLs.

**Comment by KateMJAC** [comment]
@lloback I just went back to test it and it worked as it should. So I must have used the wrong link or something. So ignore me. 

Still waiting on UTG feedback though.

**Review by KateMJAC — COMMENTED** [review]
We are still getting a mixed back on testing via the UTG on this, comments below: 

1) I have just tested this and it appears that the connection log is working fine, but the history log is not recording accurately, as we skipped questions and returned to questions but it is showing as 0.

2)Ticket 1317 - connection log worked fine and history log showed stats for all areas including times visited, saved, skipped and changed, although I don't think accurate as I didn't skip any questions and shows 1 skipped.

**Comment by joy-ade** [comment]
@lloback 
This is a comment from Kate can you look into this pls.
We are still getting a mixed back on testing via the UTG on this, comments below:

I have just tested this and it appears that the connection log is working fine, but the history log is not recording accurately, as we skipped questions and returned to questions but it is showing as 0.
2)Ticket 1317 - connection log worked fine and history log showed stats for all areas including times visited, saved, skipped and changed, although I don't think accurate as I didn't skip any questions and shows 1 skipped.

**Comment by lloback** [comment]
Hi @KateMJAC  and @joy-ade I've reviewed the code and addressed all the issues that were pending.
Please review again.

**Comment by joy-ade** [comment]
@lloback We are still getting mix feedback from UTG see comment and screen shoot below. 
I  have created and completed a scenario QT the connection logs tab correctly shows the time logged in and out. The history log is incorrect for 'amount of time on question' however the more detailed log below this does seem to be accurate.
image (5)

**Comment by KateMJAC** [comment]
@lloback following Joy's last message please find a screenshot that details specifically what went wrong here: [https://app.zenhub.com/files/201485031/55a3495d-b99b-4668-bdc5-f00169f346ee/download](https://app.zenhub.com/files/201485031/55a3495d-b99b-4668-bdc5-f00169f346ee/download)

I believe this was tested after your last post, but I will send it out again to this week's testers.

**Comment by lloback** [comment]
> @lloback following Joy's last message please find a screenshot that details specifically what went wrong here: https://app.zenhub.com/files/201485031/55a3495d-b99b-4668-bdc5-f00169f346ee/download
> 
> I believe this was tested after your last post, but I will send it out again to this week's testers.

This image has nothing to do with this task. If you want something changed on this page we need to create a ticket for it. The image you attached was an old attempt of calculating the time that people stay on each question. It takes the timestamp when you enter and then the timestamp where you leave. It is prone for errors because you may come back and the time will increase exponentially. I actually think that we should remove it from this page (I can create a task for that if you want)

If no further feedback was added to this new statistic page that we created, I would like this PR to be reviewed and approved.

@joy-ade @KateMJAC @warrensearle

**Comment by KateMJAC** [comment]
@lloback Warren dropped me a line on this ticket and I provided him with additional feedback provided by the UTG. 

He has advised that the PR can be left open for now. 

@joy-ade

**Comment by joy-ade** [comment]
@KateMJAC thank you for the update

**Comment by londonprojects** [comment]
Hello @warrensearle @lloback What is the issue here?

**Comment by warrensearle** [comment]
@lloback there is a discrepancy around what the 'changes' statistic means. It looks like we are counting every time the answer is saved however the UTG are expecting the count to be only those times the answer is changed from one value to another - i.e. excluding the first save and any skips.
We should aim to meet UTG expectations but if not possible we should update the wording so it is clear what the count represents.

**Review by tomlovesgithub — APPROVED** [review]

**Comment by lloback** [comment]
The issues were changed on the apply banch.
All merge conflicts gone.

**Comment by warrensearle** [comment]
Hey @KateMJAC @joy-ade please can you test this again

**Comment by joy-ade** [comment]
out to UTG 9/08/2021 awaiting feedbacks

**Review by joy-ade — APPROVED** [review]
Approved by product team and UTG

**Pull request merged**
