### PR TITLE
#2154 Configure working preferences questions

### LINKED ISSUE #2154: Configure working preferences questions
See Apply: [Working Preferences questions](/jac-uk/apply/issues/1072)

## Improvements to existing functionality

- [x] Working preferences questions should be mandatory (if configured)
- [x] Ranking. Should not be able to skip numbers - e.g. choosing two answers from five means user can choose 1st and 2nd choice, not 1st and 5th
- [x] Enable multiple location questions. (e.g. this will enable preferred and maybe selections)
- [x] Enable multiple jurisdiction questions. (e.g. this will enable preferred and maybe selections)
- [x] Define how many answers candidates should select
- [x] Enable linked questions
- [x] Enable grouping of answers (two levels)
- [x] Allow re-use of jurisdictions from vacancy information (for jurisdiction questions)
- [ ] Allow questions to be re-ordered (e.g. move question 3 to be question 1) 

image

## Use Jurisdictions from Vacancy Information
In the Vacancy Information part of the exercise SETs configure which jurisdictions are part of the vacancy.
Rather than enter these from scratch for the Jurisdiction question we should offer SETs a way to instead use the jurisdictions they've already configured in Vacancy Information

image

## Allow linked questions
Sometimes locations are specific to a jurisdiction (and vice versa).
To facilitate this we will allow answers to have linked questions such that if **Answer A** is chosen then the candidate will be asked the linked question for Answer A

Configure a question to have linked answers:
image

Link a question to a linked answer:
image

## Allow grouping of answers
On some occasions there are so many answers it is useful to group them
For example clusters (of courts) may be grouped into circuits, such as:
 - North East
   - Newcastle
   - Durham
   - Teesside
   - Bradford
   - Sheffield
 - North West
   - Carlisle
   - Lancaster
   - Bolton
   - Crewe
 - London
   - Fleetbank House
   - RCJ
   - Alfred Place
   - Central London
 - South East
   - Luton
   - Bedford
   - High Wycombe
   - Maidstone
   - Horsham
   - Colchester
 - South West
   - Truro
   - Plymouth
   - Gloucester
   - Bristol

Here the user is choosing the lower level answers (the clusters or courts). The groupings (circuits) are just there to aid navigation.

image

---

See the following [visuals](
https://www.figma.com/file/aqILfbMFEy51XDaFZpid8i/Ranked-answers-with-linked-questions?type=design&mode=design)

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?
Additional configuration options for working preferences questions, as follows:

- [x] Enable multiple location questions. (e.g. this will enable preferred and maybe selections)
- [x] Enable multiple jurisdiction questions. (e.g. this will enable preferred and maybe selections)
- [x] Define how many answers candidates should select
- [x] Enable linked questions (e.g. if a particular answer is chosen then the user is asked a follow-on question)
- [x] Enable grouping of answers (two levels)
- [x] Allow re-use of jurisdictions from vacancy information (for jurisdiction questions)

Closes #2154 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

We decided to continue to support current functionality for existing exercises and have new exercises benefit from the new functionality.

There are therefore two areas to test:

**1. There should not be any breaking changes for existing exercises**

Either pick an existing exercise that is configured with the original working preferences OR use the main [admin-develop](https://admin-develop.judicialappointments.digital/) url to create a new exercise and configure working preferences for it.

View the chosen/created exercise on the [Preview URL](https://jac-admin-develop--pr2207-feature-2154-d8s2h7zf.web.app/) and check that working preferences works as expected (as it does on admin-develop). For example you could have admin-develop and preview url running in separate windows and compare the functionality side by side.

You should be able to:

 - Configure and edit one location preference
 - Configure and edit one jurisdiction preference
 - Configure and edit multiple additional preferences
 - View a candidate's chosen preferences on their application
 - Edit a candidate's chosen preferences on their application (in 'edit mode')

_Note: you may like to create an application via [apply-develop](https://apply-develop.judicialappointments.digital/) so you can test viewing and editing applications._

Please highlight any breaking changes.

**2. New exercises should benefit from the new functionality and the new functionality satisfies user requirements**

Using the [Preview URL](https://jac-admin-develop--pr2207-feature-2154-d8s2h7zf.web.app/) please create a new exercise and check that the new working preferences functionality is available.

In particular check that the following functionality works as expected and also that the terminology and instructions provided are sufficiently clear.

1. Check that you can add multiple location questions
4. Check that you can add multiple jurisdiction questions
5. Check that you can define how many answers candidates should select (for multiple and ranked choice questions)
6. Check that you can create a linked / follow-on question (where if a user selects one answer they are asked a follow-on question)
7. Check that you can group answers
8. Check that, for jurisdiction questions, you can choose to use the exercise jurisdictions list instead of re-entering the data

_Note: when you have tested the above please test [this PR on Apply](https://github.com/jac-uk/apply/pull/1135) so that you have an application with the latest preferences data._

Then back in Admin continue to test the following in Applications:

9. Check that all working preferences answers are displayed correctly on the candidate's application
10. Check that all working preferences can be edited when the application is in 'edit mode'

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Review by drieJAC — COMMENTED** [review]
The first time I loaded the JAC00708 exercise and clicked on Working Preferences it didn't display the list of questions, so I assumed it didnt have any. I added a few questions then when I went back to the Working Preferences screen it displayed a longer list of questions.
Could it be that the questions are not loaded in the store when the page initially loads?
Also when I click on the Working Preferences tab for JAC00707 I just get an empty page with Working Preferences as the title.

**Comment by warrensearle** [comment]
> The first time I loaded the JAC00708 exercise and clicked on Working Preferences it didn't display the list of questions, so I assumed it didnt have any. I added a few questions then when I went back to the Working Preferences screen it displayed a longer list of questions. Could it be that the questions are not loaded in the store when the page initially loads? Also when I click on the Working Preferences tab for JAC00707 I just get an empty page with Working Preferences as the title.

Ha I created that exercise today and I think you must have been trying to use it at the same time as I was populating it with content!

**Comment by warrensearle** [comment]
> @warrensearle From my initial testing, functionality appears to work well. My main feedback is - not fully understanding the different types of questions - it feels like it would be useful to have a bit more explanation around the different options. Either that, some examples or a linked download that users can refer to for examples of different question set-ups.

Yes we could elaborate on the question types. Happy to go with whatever you and the users want. I guess the quickest is adding in a bit of text for each option or a link to an external document.

What would be better (in addition) would be to have a live preview of what the page will look like. Then our users can try things out and see the results straight away. This could be achieved fairly easily if we are smart about it and I'd suggest we do it for the whole application form rather than individual parts of it.

> One minor comment: I wonder if we should make increase the font size of the tabs; it's quite easy to overlook them?

I haven't given the UI much love - just using the existing components we have with their default styles. I agree the font sizing could do with some refinement plus the positioning (and perhaps style) of the 'remove' buttons

Rather than going bigger with fonts I think perhaps the field labels (questions) could be smaller, which is more in line with what [GDS recommend](https://design-system.service.gov.uk/components/text-input/)

We are currently using large field labels (GDS recommends this for single field per page)
image


We could use smaller field labels (GDS recommends for multiple fields per page)
image

**Review by HalcyonJAC — APPROVED** [review]
All functionalities work 👍

**Review by NormaJAC — COMMENTED** [review]
I was able to perform all required steps

**Comment by nickaddy** [comment]
@warrensearle Passed UT, but need to factor in some input from Matt:

- [ ] When setting up the location questions, you can allow them to have linked questions, but there doesn’t seem to be an option to create the follow-on questions
- [ ] The option to select how many questions candidates need to select, sets a minimum number, not a definitive number candidates should select: is this what we want? In an ideal world, the options would be ‘Any’, ‘At least’ and ‘Exactly’
- [ ] Having mandated all fields, we have left no option for candidates to not select at least one answer within each question. So for example, if we wanted question 1 to be ‘Rank your top 3 cluster preferences’ and question 2 to be ‘Select any other clusters you would consider’, it is only the first question we need candidates to specify an answer to; the second question is intended as a free for all – some candidates might not consider working at any other cluster. We can work around this by including a ‘None of the above’ option.

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Comment by warrensearle** [comment]
UT feedback:
 - [ ] Check that we can set up jurisdiction questions with linked location questions and also the other around. Feedback suggested this was not flexible and was only possible one way round.

**Review by nickaddy — APPROVED** [review]
@warrensearle As far as I can tell this is doing what was intended. I think it might be useful to present some examples of the different configurations to users. I found 'Is this a required question?' a bit confusing. Presumably, if it wasn't required, you wouldn't be putting it in?

**Comment by warrensearle** [comment]
@nickaddy 

> I think it might be useful to present some examples of the different configurations to users. I found 'Is this a required question?' a bit confusing. Presumably, if it wasn't required, you wouldn't be putting it in?

Please let us know any changes/additions you'd like to the on-screen instructions. Alternatively we could put them in a new ticket for the next iteration.

**Comment by nickaddy** [comment]
@warrensearle As keen as I am to see the back of this, I cannot see half of this functionality on the preview url - I was testing on [this exercise](https://jac-admin-develop--pr2207-feature-2154-d8s2h7zf.web.app/exercise/8MffSchSALJcaEKE1Y3O/details/overview). I couldn't see any options to:

- Define how many answers candidates should select
- Enable linked questions (e.g. if a particular answer is chosen then the user is asked a follow-on question)
- Enable grouping of answers (two levels)
-  Allow re-use of jurisdictions from vacancy information (for jurisdiction questions)

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Comment by nickaddy** [comment]
@warrensearle there seems to be an issue with saving after editing a candidate's loc or juri preference; the button turns yellow but does not disappear and when you click Done, changed answers have not been saved.

**Comment by nickaddy** [comment]
@warrensearle Interestingly, I just submitted a new application and I did not experience the issue above - I was able to edit and save all responses.

**Comment by warrensearle** [comment]
I propose closing this ticket and moving any future changes or bugs to new tickets.

Note that I have re-opened the following two tickets as the described functionality needs to be updated with changes/simplifications made in this pull request:

https://github.com/jac-uk/admin/issues/2318

https://github.com/jac-uk/admin/issues/2319

**Comment by warrensearle** [comment]
@nickaddy please can you approve this PR, particularly if you agree with the above suggestion

**Review by nickaddy — APPROVED** [review]

**Review by HalcyonJAC — APPROVED** [review]

**Review by NormaJAC — APPROVED** [review]

**Pull request merged**
