### PR TITLE
Bugfix/User role with Microsoft email address

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Fix the bug when a new user signs in with Microsoft email address.

## Who should test?
✅ Product owner
✅ Developers

## How to test?
Describe the steps required to test & verify this change

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work
🟠 Medium risk - this does change code that is shared with other areas
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by tomlovesgithub — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC Not quite sure how or what I'm testing here?

**Comment by HalcyonJAC** [comment]
@nickaddy I have updated the test instructions. Could we find a new user with a Microsoft email?

**Comment by nickaddy** [comment]
@HalcyonJAC This is a brand new user, starting this week or last: sana.bux@judicialappointments.gov.uk

**Comment by nickaddy** [comment]
@HalcyonJAC Tested with Sana, still receiving the same error: 

image

Clicking the first link just cycles back round again.

**Pull request merged**
