### PR TITLE
2229/ra report updates

### LINKED ISSUE #2229: Updates to Reasonable Adjustments
**Background**
At the Digital Team meeting on 28/11/23, a number of improvements to Reasonable Adjustments (RA) pages were proposed. The ideal opportunity to test out/utilise this functionality will be on the Disability Members exercise (181) launching on 13 March 2024. NA has reached out to Sean Conway for input as an experienced user and he is going to review in early January, when he has more time available. **Hence, this work will take place later in January sprint.**

**Feature(s) Description** 

- [x] 1. Default display should included details of RA submitted by candidate on the current exercise in question (user can still click 'View all reasonable adjustments' to view RA requests submitted by candidate on other exercises)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c1d7f8d0de29945955505f5efcaf5c2dd0c71a9/image.png)

- [x] 2. Details of RAs agreed on previous exercises should be listed alongside RA requests from previous exercises (visible when user expands 'View all reasonable adjustments'

- [x] 3. Amend naming of onscreen fields

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82103e97ad12169a90223c1aaec6a0a0d3fabb61/image.png)

Status > Approval status
Where the reasonable adjustments was given > Activity for which reasonable adjustment given
Unnamed box > Describe reasonable adjustment given

- [x] 4. Add new dropdown field named Reasonable adjustment allocated (time), options listed below:

5% additional time
10% additional time
15% additional time
20% additional time
25% additional time
30% additional time
40% additional time
50% additional time

- [x] 5. Repair search function and add guidance on what fields can be searched as per standard search functionality across platform

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f434dd6a1ec2d831c5b7d3e722c39557e7bcc75a/image.png)

- [x] 6. Repair 'Where reasonable adjustments given' dropdown - does not display option chosen onRelease

- [x] 7. Add candidate email and phone contact details to the onscreen display, suggested location next to name:

- [x] 8. Amend RA report:
* Rename **Details** column to **Details provided by candidate**
* Add column **Agreed Reasonable Adjustments** - this should display the content from the 'Describe reasonable adjustment given' field, completed by SET
* Remove columns: **Most recent exercise** and **Most recent details**

- [x] 9. Add a button **No further reasonable adjustments to add** to the right of **Add another** button - user clicks this button once they have allocated all RAs (QT, ST and SD) as appropriate. Once that button is clicked, that candidate will disappear from the list.

**User Testing Steps**
Add instructions here

**Ticket Champion**
Sean Conway

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
Numerous changes to the RA report;
- Display shows IA details for current exercise 
- On screen fields given clear labels
- Additional drop down to allocate RA given as a %
- Fixed search functionality
- Candidate Email and Telephone number displayed next to name to contact
- Facility to flag candidates as actioned and filter actioned candidates from the view

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Not ready for pass/fail testing.

Please advise testers to interact with the page and give feedback for improvements and changes to make the feature more useful 

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

Closes #2229 
---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@tomlovesgithub Can you pls factor in these outputs from last week's UT/myself:

- [ ] When you click the application hyperlink it takes you directly to the issues tab, it be more beneficial to go to the full information tab
- [ ] Add labels to the dropdown filters - `Status `and `RA Approval Status`

- [ ] Resolve the alignment at the top - is it possible to have the filters and the checkbox all on the same row?

**Comment by nickaddy** [comment]
Further feedback to implement:

- [ ] Selecting an option from the Application Status dropdown causes another dropdown to appear, which is misaligned, and a Loading timer – the page then freezes as shown:



- [ ] From a UI perspective, there should be more whitespace between the 3 dropdown menus at the top of the page; they are currently all squashed together with the result that they’re not easy to read

- [ ] Candidate names in column A of download should be in format Lastname, Firstname

- [ ] `Approval status`, `RA allocated` and `RA description` data is not appearing in the download

- [ ] `RA applies to` column needs to be included in download

**Comment by KoWeiJAC** [comment]
@nickaddy 
Could you help me to confirm the RA report format when having multiple RA items ? Thanks
Is following format ok?

**Review by NormaJAC — APPROVED** [review]

**Review by HalcyonJAC — APPROVED** [review]
👍

**Pull request merged**
