### PR TITLE
Signage for unpublished exercises

### LINKED ISSUE #2023: Signage for unpublished exercises
An admin raised an issue whereby the updating of details on a live exercise unintentionally caused the exercise to become unpublished and unseen by candidates, this only became evident once candidates contacted to ask if/why the exercise was closed. 

In order to remedy this some changes should be made to the overview page;

- [x] Increase the font size of "Published"/"Unpublished" in the blue status box (top of page)
- [x] Move "Congratulations! This exercise has been approved. Now you can publish it to the website." into a banner component and place at the top of the page.
- [x] Insert a warning banner that appears when an exercise is in an "unpublished" state whilst within the application window.

....Bonus
- [x] fix "webstite" spelling error

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
- Increase the font size of "Published"/"Unpublished" in the blue status box (top of page)
- Move "Congratulations! This exercise has been approved. Now you can publish it to the website." into a banner component and place at the top of the page.
- Insert a warning banner that appears when an exercise is in an "unpublished" state whilst within the application window.
- fix "webstite" spelling error

closes #2023 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Check exercise approval and publishing process for the above changes. 

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by nickaddy — COMMENTED** [review]
Happy to approve on the basis that these are cosmetic changes only. If user-testing, would be useful to have dummy exercise ready to approve.

**Review by HalcyonJAC — APPROVED** [review]
Code looks good to me 👍

**Review by warrensearle — CHANGES_REQUESTED** [review]
Please see the change here: https://github.com/jac-uk/admin/pull/2090

This means there is empty space on the right where the 'change stage' link used to be. Would suggest using this space to display the published / un-published state of the exercise rather than having everything stacked on the left as it currently is:
image

**Comment by tomlovesgithub** [comment]
> Please see the change here: #2090
> 
> This means there is empty space on the right where the 'change stage' link used to be. Would suggest using this space to display the published / un-published state of the exercise rather than having everything stacked on the left as it currently is: image Could even put the Publish / Un-publish button here too

Hey Warren, sorted it - i think, please feel free to amend or merge while im away

**Review by warrensearle — APPROVED** [review]

**Comment by warrensearle** [comment]
Hey @tomlovesgithub just tweaked it slightly to try to avoid confusion between publish and unlock:

**Before**
image

**Now**
image

**Pull request merged**
