### PR TITLE
Feature/2505 Apply user role filters on Exercise contacts page

### LINKED ISSUE #2505: Apply user role filters on Exercise contacts page
## Background
Currently the JAC contacts dropdowns on the Exercise contacts page include all JAC users. We would like to filter them by role so that only relevant staff are included as per [the Gantt chart filters](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2458).

## User Story
As an Admin, I would like the JAC contacts lists to be filtered to include only the relevant staff so that it is easier to find the right contact in the list.

## Feature(s) Description
- [x] Filter the Senior Selection Exercise Manager dropdown by Ops senior manager role
- [x] Filter the Selection Exercise Manager dropdown by Ops team member role
- [x] Filter the Selection Exercise Officer dropdown by Ops team member role

## Acceptance Criteria 
It's done when the three dropdowns are filtered as above

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2505 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
[Example exercise](https://jac-admin-develop--pr2510-feature-2505-apply-u-cilfp82k.web.app/exercise/TSZHvLiBpittnlOXmMlI/details/contacts/?referrer=exercise-show-overview)

Steps:
1. Go to the exercise contacts page.
2. Amend the "Senior selection exercise manager" fields and check if only users with the "Operations Senior Manager" role appear in the dropdown.
3. Amend the following fields and check if only users with the "Operations Team Member" role appear in the dropdown.
    - Selection exercise manager
    - Selection exercise officers

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by KoWeiJAC — APPROVED** [review]

**Comment by nickaddy** [comment]
@HalcyonJAC Could you create a preview URL on Admin Production pls? We don't have all the user groups set up on Develop, hence it's not possible to fully test this ticket.

**Comment by HalcyonJAC** [comment]
> @HalcyonJAC Could you create a preview URL on Admin Production pls? We don't have all the user groups set up on Develop, hence it's not possible to fully test this ticket.

@nickaddy here is the [preview link on production](https://jac-apply-admin-production--pr2510-feature-2505-apply-1ut29iwh.web.app/).

**Comment by nickaddy** [comment]
@HalcyonJAC The Senior dropdown is not working for me - this should be filtered by Ops Senior Manager role. Could you fix pls?

**Comment by HalcyonJAC** [comment]
@nickaddy It has been sorted. Could you test it again, please?

**Review by nickaddy — APPROVED** [review]
👍

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
