### PR TITLE
#1719 Candidate flagging

### PR DESCRIPTION
**Pull request by drieJAC**
## What's included?
Added a flag to indicate that particular candidates on the system need to be handled sensitively.
Added a permission to determine who can see the button to flag/un-flag a candidate as needing to be handled sensitively.
An asterisk will appear next to their name on certain pages and an email is sent to the senior leadership team when they apply for a position.
Note that the candidates flagged/marked are usually involved with proceeding against the JAC and the management of their application needs to be handed sensitively. Having this will ensure a consistent approach and that any sensitive issues are dealt with correctly.

The email addresses of users who need to be notified when a candidate is flagged should be added to the firestore config. An array of email addresses can be added at: `settings.services.emails.CandidateFlagging`

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

**Flagging / Un-flagging a candidate**

Please log in as a user with the 'Can flag candidates' permission - e.g. seniorleader@judicialappointments.digital

To flag/unflag a candidate go to the Candidate page and select the Notes tab. A flag/unflag button is displayed on the right hand side. This button should toggle between the flag and unflag states each time it is clicked.

When the user is flagged an email should be sent out to the senior leadership team. This email should only get sent once, ie repeat activation of the flag should not result in subsequent emails being sent.

Please log in as a user without the 'Can flag candidates' permission - e.g. jacstaff@judicialappointments.digital
Check that the Flag / Un-flag functionality is not present.

**Identifying flagged candidates**

The flagged candidates should have an asterisk on the following pages for all users:

- Candidates list (asterisk appears next to the candidate's name)
- Candidate page (asterisk appears next to the candidate's name)
- Application page (asterisk appears next to the application's name)

On the Candidates list you can press the Show Filters button to display a checkbox allowing you to filter by 'flagged candidates only'. When this filter is activated only the flagged candidates should display in the list.

**Additional Fix**
In the Candidate page the 'edit' button should now only be displayed when the Details tab is active. Previously the edit button was showing on every tab.

## Permissions
A new permission has been added. The user needs to have the 'Can flag candidates' permission checked in order to be able to flag/unflag candidates.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by warrensearle** [comment]
Failed User Testing for the following reasons:
 - Filtering the candidates list not working (wheel of death)
 - Flag not showing on applications list (acceptable as future work)

Also we have the following questions:
 - Should staff be required to enter a Note (or should an automated note be added)?

**Comment by andrew-isaac** [comment]
Admin stated they couldn't see the option to flag candidates. I have not tested the pull request myself to comment but adding the feedback in.

**Comment by warrensearle** [comment]
Recent updates to permissions and demo users mean this should be easier to test now. 🤞 
Instructions updated.

**Review by HalcyonJAC — APPROVED** [review]
Code looks great to me 👍

**Review by warrensearle — APPROVED** [review]
👍

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
