### PR TITLE
Feature/2419 Reference statuses in Independent Assessments task

### LINKED ISSUE #2419: Reference statuses in Independent Assessments task
## Background
Since the **Review** stage was consolidated into **Shortlisting**, users are unable to select only candidates that have passed the QT in order to request IAs for those candidates only. This relates to the recent changes to Stages & Statuses.

## User Story
As an Admin, I would like to be able to select only candidates that have passed the QT so that I can request Independent Assessments ahead of the sift taking place. Currently, the dropdown is linked to Stages, however, it needs to be linked to Statuses.

## Feature(s) Description
- [x] When initiating the IA task, the dropdown menu must reference candidate statuses, e.g. QT passed, and candidates with the select status should appear in the list on screen when `Start assessments` button is pressed

## Acceptance Criteria 
It's done when Admins can select candidates by status and then send IA requests to assessors for those selected candidates.

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
Specify for users what is being tested (but not how to test it.)

## Feature Champion
Tracey

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
Closes #2419 

Related PRs:
- [digital-platform: Feature/admin 2419 Reference statuses in Independent Assessments task #1110](https://github.com/jac-uk/digital-platform/pull/1110)
- [digital-platform: Feature/admin 2419 Reference statuses in Independent Assessments task #1114](https://github.com/jac-uk/digital-platform/pull/1114)

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
Example exercises: 
- [Ryan test 1 (Character issues)](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/IbeEVi4Vtrpv9eVFzhZq/tasks/all/independent-assessments)
- [Ryan test 2 (Character issues)](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/FpV4enhw0yWFb9htWO7y/tasks/all/independent-assessments)
- [Ryan test 3 (Character issues)](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/DVGGSXxY0MdhbehA1R98/tasks/all/independent-assessments)
- [Ryan test 4 (Character issues)](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/XEu94ZOPGM1PRZuEhUdH/tasks/all/independent-assessments)
- [Ryan test 5 (Character issues)](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/g45SG9vPFlhInL6yDonh/tasks/all/independent-assessments)

Steps:
1. Go to the Independent Assessments task.
2. Check if the options and counts in the dropdown are generated based on the application statuses.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Demo:

https://github.com/jac-uk/admin/assets/79906532/2ed7b9f8-b25c-479d-acec-15ffa3448ca9

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@HalcyonJAC I believe this works, however, I just had a thought: this may never happen, but if there was a case where there was a small exercise and IAs was the first task, i.e. no QT, no sift before, would the application status appear as blank in the dropdown? And, if so, would users be able to select and progress all candidates with a blank status?

**Comment by HalcyonJAC** [comment]
@nickaddy That case might happen indeed. For now, the blank status will not appear in the dropdown. I could make changes to support selecting candidates with a blank status if you would like.

**Comment by nickaddy** [comment]
@HalcyonJAC Better safe than sorry! Pls proceed with including the 'blank' option in the dropdown.

**Comment by HalcyonJAC** [comment]
@nickaddy The `Blank` option is included in the dropdown. Could you test it, please?

**Review by nickaddy — APPROVED** [review]
@HalcyonJAC That works great, thx for the extra work on this :-) 

I tested on [this exercise](https://jac-admin-develop--pr2420-feature-2419-referen-7tqgsgb3.web.app/exercise/IbeEVi4Vtrpv9eVFzhZq/tasks/all/independent-assessments) - could you roll back to the beginning of the task for UT pls?

**Review by NormaJAC — APPROVED** [review]
It works

**Review by Franceswog — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
