### PR TITLE
#2475 Introduce Processing Version 3.0

### LINKED ISSUE #2475: Introduce Processing Version 3.0
In 'Processing version 2.0' we introduced a new set of stages and statuses.

Here we are introducing 'Processing version 3.0' which will include new Tasks (PSDQ, Sift, Selection Day etc).

_Note the new tasks were previously included in version 2 and causing confusion for SETs so this change will resolve that._

**To Do**

- [x] Add Processing version 3.0 to the configuration area in Admin (see screen grab below)
- [x] Update code to ensure new tasks only show for version 3+
- [x] Ensure Exercise > Additional Settings only shows for version 3+
- [x] Ensure the stage & status migration code only runs when changing between version 1 and 2 (not for changes to version 3+)

**Config page**

**Tasks for 2.0**

**Tasks for 3.0**

### PR DESCRIPTION
**Pull request by warrensearle**
## What's included?
In 'Processing version 2.0' we introduced a new set of stages and statuses.

Here we are introducing 'Processing version 3.0' which will include new Tasks (PSDQ, Sift, Selection Day etc).

_Note the new tasks were previously included in version 2 and causing confusion for SETs so this change will resolve that._

**To Do**

- [x] Add Processing version 3.0 to the configuration area in Admin (see screen grab below)
- [x] Ensure new tasks only show for version 3+
- [x] Ensure Exercise > Additional Settings only shows for version 3+

**Config page**

**Tasks for 2.0**

**Tasks for 3.0**

Closes #2475

## Who should test?
✅ Product owner

## How to test?
Try changing processing version to 3.0 and check new tasks appear and nothing blows up! 
Try changing back to 2.0 and back again to 3.0 to try to get it to blow up 😄 

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@warrensearle I'm getting the Fb error on the preview url
image

**Comment by warrensearle** [comment]
> @warrensearle I'm getting the Fb error on the preview url 

@nickaddy please refresh and try again

**Review by HalcyonJAC — APPROVED** [review]
I have tested the following items and they work well 👍
- Change processing version to 3.0 and new tasks appear.
- Change back to 2.0 and new tasks disappear.

**Review by nickaddy — APPROVED** [review]
Does what it says on the can, @warrensearle! Will we be able to 'turn on' that functionality for current exercises on v2, once it is fully up and running?

**Comment by warrensearle** [comment]
> Does what it says on the can, @warrensearle! Will we be able to 'turn on' that functionality for current exercises on v2, once it is fully up and running?

Yes exactly @nickaddy and at some point, if we want, we can run a script to move every v2 to v3

**Pull request merged**
