### PR TITLE
Feat/2254 streamlined publication of external adverts

### LINKED ISSUE #2254: Streamlined publication of external adverts
**Background**
Matt was trying to publish an external advert and noted that the workflow was unnecessarily complicated. 

**User Story** 
As an admin, I would like to be able to publish an external advert without going through the approval process so that publication is simpler.
 
**Feature(s) Description** 
-	Remove the need for approval if an advert type is External
-	Un-mandate all advert fields except for _Name, Open Date, Close Date, Brief overview (listing), Advert type_

**Ticket Champion**
Matt Howley

**Happy Story (optional/delete if not used)**
To be able to Edit  and publish external adverts in a seamless manner onto the platform.

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
Closes #2254 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link: https://jac-admin-develop--pr2301-feat-2254-streamline-0we56wtz.web.app/exercises
- Create external vacancy:
    - click `Create an exercise`
Screenshot 2024-02-06 at 16 39 33

    - Choose `No - this is an external vacancy` and save.

Screenshot 2024-02-06 at 16 41 06

    - It should create an draft external vacancy and show overview of the vacancy.
- Edit external vacancy
    - Go to vacancy overview. (Click the exercise, if you're in the exercise list https://jac-admin-develop--pr2301-feat-2254-streamline-0we56wtz.web.app/exercises)
    - Click `update`, it should show edit page.
    
Screenshot 2024-02-06 at 16 44 41

    - Enter data and click save, if should save those data.
- Publish external vacancy
    - Go to vacancy overview. (Click the exercise, if you're in the exercise list https://jac-admin-develop--pr2301-feat-2254-streamline-0we56wtz.web.app/exercises)
    - Scroll down, there's a `Publish on website` button under the files downloads.
   
Screenshot 2024-02-06 at 16 51 13

    - Click the `Publish on website`, it should be posted on the apply site.
   

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by nickaddy** [comment]
@KoWeiJAC @MattHowley to test this

**Review by drieJAC — COMMENTED** [review]
The back button doesnt seem to work from this page:

https://jac-admin-develop--pr2301-feat-2254-streamline-0we56wtz.web.app/exercise/c2Eid1ck9Et6gZs0Dyxw/externals/

**Comment by HalcyonJAC** [comment]
@drieJAC I have fixed the back button. Could you test it again, please?

**Review by NormaJAC — COMMENTED** [review]
Created the external advert, it is listed on Apply - steps worked as expected.

**Review by tomlovesgithub — APPROVED** [review]

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
