### PR TITLE
Feat/admin 2396 create scc eligibility download for legal exercises

### LINKED ISSUE #2396: Create SCC Eligibility download covering 3 annexes for legal exercises
## Background
This ticket is connected with [#2387](https://app.zenhub.com/workspaces/platform-development-5ea838cd2aec471eb6d14139/issues/gh/jac-uk/admin/2387), in which the `Eligibility report` display has been reconfigured to focus on specific areas of eligibility for legal exercises only, due to the fact that non-legal exercises are problematic thanks to the lack of distinction between statutory and ASC criteria, and reviews that are currently taking place. Hence, we aim to automate production of the following annexes for legal exercises only: Statutory eligibility criteria (Professional qualification and PQE), PJE and RLoS.

## User Story
As an Admin, I would like to be able to download SCC Annex-ready eligibility annexes so that I can expedite production of the SCC paper.

## Benefit(s) to user (if not already clear from User story)
Admins will be able to produce a Word download from the platform that covers some of the eligibility annexes required for the SCC report.

## Feature(s) Description

- [ ] The annexes described below should be produced as a single Word document download which is downloaded to user's desktop when you click the Download SCC Annex report button
- [ ] Each section of the report should be preceded by a page break
- [ ] The first section of the annex 'Candidates who do not meet the Statutory Eligibility Criteria' includes candidates who are 'Not met' for Professional qualification and/or Post-qualification experience **sorted alphabetically by candidate surname**

- [ ] The content for the 'Reasons Statutory Eligibility Criteria is not satisfied' column is drawn from the 'Reasons not satisfied' field for Statutory eligibility criteria

- [ ] The content for the next two sections is Candidate Previous Judicial Experience and plays back this section of the Eligibility report

- [ ] It is split into 3 sections 'Recommended to proceed', 'Recommended to discuss', and 'Recommended to reject' according to the Recommendation selected from the dropdown in that section

- [ ] The final section relates to Reasonable Length of Service and includes all candidates with a Not Met flag under RLoS **ordered alphabetically by their surname**

- [ ] It is formatted as below

- [ ] Column C returns candidates' ages at date that SCC is scheduled for (this has already been calculated by the platform to determine whether they meet the RLoS criteria or not)

## Acceptance Criteria 
It's done when for legal exercises only:
- [ ] Users can trigger a download to their desktop based on the criteria described above
- [ ] Each section starts on a fresh page
- [ ] Each section is ordered alphabetically by candidates' surnames
- [ ] Each section is formatted according to the images presented
- [ ] Each section included the content as described
- [ ] The PJE section is split into Proceed, Discuss and Reject sub-sections

## Definition of Done
- [ ] User stories/acceptance criteria met
- [ ] Internal reviews passed (feedback actioned)
- [ ] User testing passed
- [ ] Relevant technical documentation updated
- [ ] User guidance updated
- [ ] Deployed and merged without errors

## User Testing Steps
This feature is designed to automate as much of the production and formatting of the eligibility report as possible for legal exercises. Does the functionality deliver what is required to produce the annexes covering: 1) statutory eligibility criteria, 2) PJE and 3) Reasonable length of service?

## Feature Champion
Nick

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
closes #2396 

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Go to the preview link: https://jac-admin-develop--pr2400-feat-admin-2396-crea-rjpjdx45.web.app/exercise/S9V9R15MGRjCDHdcRQRZ/reports/eligibility-issues
- Click  `Download SCC Annex report`  to download the report
- Check contents of following sections are correct
    - Candidates who do not meet the Statutory Eligibility Criteria
    - Candidates recommended to proceed and the reasons why they are considered to meet the ASC - Previous Judicial Experience
    - Candidates recommended to discuss and the reasons why they are considered to potentially meet the ASC - Previous Judicial Experience, necessary skills in some other significant way
    - Candidates recommended to reject and the reasons why they are considered to not meet the ASC - Previous Judicial Experience through a quasi-judicial role or showing the skills in some other significant way  Candidates who will not be able to provide 3 years reasonable service when recommendations are made to the Lord Chancellor

Example exercises:
- [Ryan test 1 (Character issues)](https://jac-admin-develop--pr2400-feat-admin-2396-crea-rjpjdx45.web.app/exercise/IbeEVi4Vtrpv9eVFzhZq/reports/eligibility-issues)
- [Ryan test 2 (Character issues)](https://jac-admin-develop--pr2400-feat-admin-2396-crea-rjpjdx45.web.app/exercise/FpV4enhw0yWFb9htWO7y/reports/eligibility-issues)
- [Ryan test 3 (Character issues)](https://jac-admin-develop--pr2400-feat-admin-2396-crea-rjpjdx45.web.app/exercise/DVGGSXxY0MdhbehA1R98/reports/eligibility-issues)
- [Ryan test 4 (Character issues)](https://jac-admin-develop--pr2400-feat-admin-2396-crea-rjpjdx45.web.app/exercise/XEu94ZOPGM1PRZuEhUdH/reports/eligibility-issues)
- [Ryan test 5 (Character issues)](https://jac-admin-develop--pr2400-feat-admin-2396-crea-rjpjdx45.web.app/exercise/g45SG9vPFlhInL6yDonh/reports/eligibility-issues)

🟢 No risk - this is a self-contained piece of work

## Additional context
Include screen grabs, video demo, notes etc.

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required
- Permissions have been added / updated. Details:

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by drieJAC — APPROVED** [review]

**Review by NormaJAC — APPROVED** [review]
All fields correspond with the appropriate fields.

**Review by tomlovesgithub — APPROVED** [review]

**Review by Franceswog — APPROVED** [review]

**Review by nickaddy — CHANGES_REQUESTED** [review]
@KoWeiJAC Looking good, but requires some changes; could you address the following pls:

- Candidate comments (in second and third annexes) should not appear in the download if there is no content in them
- The Recommendation column of the RLoS annex should include the selection in the recommendation dropdown as well as the content of the free text field, e.g. Reject (new line) Candidate will only be able to deliver 1 year of service.
- I've checked the age calculation and it doesn't look quite right - can you confirm which date is being referenced in the calculation in the case of this exercise?

**Comment by KoWeiJAC** [comment]
> * I've checked the age calculation and it doesn't look quite right - can you confirm which date is being referenced in the calculation in the case of this exercise?

@nickaddy 

The SCC age currently is the length between the candidate date of birth and the expected service end date (Eligibility SCC date + reasonable length of service).

For example, if the Eligibility SCC date is 20 June 2024, and the reasonable length of service is 5 years.
The expected service end date is June 2029.
If the candidate date of birth is JAN 1980, the SCC age will be 49 years and 7 months old.

**Comment by nickaddy** [comment]
@KoWeiJAC Hopefully there are my final comments on the download:

-	Amend name of download to, e.g. JAC00787_SCC Eligibility Annexes
-	Age calculation in 3rd column of final annex (see below) should just be the candidate’s age on the `Character and Selection SCC` date (specified in the exercise set-up)
-	Remove text in red

image

**Comment by KoWeiJAC** [comment]
@nickaddy 
These places have been updated, could you help me to review them again? Thanks
- Candidate comments (in second and third annexes) should not appear in the download if there is no content in them
- The Recommendation column of the RLoS annex should include the selection in the recommendation dropdown as well as the content of the free text field, e.g. Reject (new line) Candidate will only be able to deliver 1 year of service.
- Amend name of download to, e.g. JAC00787_SCC Eligibility Annexes
- Age calculation in 3rd column of final annex (see below) should just be the candidate’s age on the Character and Selection - SCC date (specified in the exercise set-up)
Remove text in red

**Review by nickaddy — APPROVED** [review]
@KoWeiJAC Thanks for your patience on this ticket - it's looking great. We can now move forward to testing it on some live exercises :-)

**Comment by nickaddy** [comment]
@HalcyonJAC I cannot do a final review on Ko Wei's work because the download appears to be broken - pls repair and let me know when I can retest.

**Pull request merged**
